[package]
name = "ftty"
version = "0.1.0"
edition = "2024"
authors = ["xifan2333 <xifan233@163.com>"]
description = "Ultra-lightweight, Suckless Wayland terminal emulator with native Kitty graphics protocol, written in Rust"
license = "GPL-3.0-only"
repository = "https://github.com/xifan2333/ftty"
homepage = "https://github.com/xifan2333/ftty"
readme = "README.md"
keywords = ["terminal", "wayland", "kitty-graphics", "suckless", "emulator"]
categories = ["command-line-utilities"]

[dependencies]
bitflags = "2.8"
calloop = { version = "0.14", features = ["signals"] }
calloop-wayland-source = "0.4"
font-kit = "0.14"
fontdue = "0.9"
glow = "0.18"
khronos-egl = { version = "6.0", features = ["1_5", "dynamic"] }
libc = "0.2"
nix = { version = "0.31", default-features = false, features = [
  "term",
  "process",
  "signal",
  "fs",
  "ioctl",
  "poll",
] }
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"
unicode-width = "0.2"
vte = "0.15"
wayland-client = "0.31"
wayland-egl = "0.32"
wayland-protocols = { version = "0.32", features = [
  "client",
  "wayland-client",
] }
xkbcommon = { version = "0.9", features = ["wayland"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
