//! ANSI / VT escape sequence parser implementing the DEC terminal state machine.

pub(crate) mod csi;
pub(crate) mod osc;
pub(crate) mod sgr;

#[cfg(test)]
mod tests;

use std::collections::{HashMap, VecDeque};
use std::path::PathBuf;
use std::rc::Rc;

pub use vte::Parser;
use vte::{Params, Perform};

use crate::color::{Color, Rgb};
use crate::grid::{CellFlags, ClearMode, Grid};
use crate::input::mouse::MouseState;

pub(crate) const MAX_HYPERLINKS: usize = 1024;

/// Semantic shell integration state reported through OSC 133.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShellIntegrationState {
    PromptStart,
    CommandStart,
    OutputStart,
    CommandFinished(Option<i32>),
}

/// Progress bar notification state (OSC 9;4).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProgressState {
    Normal(u8),
    Error(u8),
    Indeterminate,
    Warning(u8),
}

/// Terminal emulation state machine combining a screen grid, current formatting attributes,
/// and a VT parser.
pub struct Terminal {
    pub grid: Grid,
    pub active_fg: Color,
    pub active_bg: Color,
    pub active_underline_color: Color,
    pub active_flags: CellFlags,
    pub mouse: MouseState,
    pub title: String,
    pub title_dirty: bool,
    /// Cell size in physical pixels, reported back through `CSI 16 t`.
    pub cell_pixels: [u16; 2],
    /// Text-area size in physical pixels, reported back through `CSI 14 t`.
    pub viewport_pixels: [u16; 2],
    pub default_fg: Rgb,
    pub default_bg: Rgb,
    pub initial_default_fg: Rgb,
    pub initial_default_bg: Rgb,
    pub palette: [Rgb; 256],
    pub initial_palette: [Rgb; 256],
    pub palette_dirty: bool,
    /// Whether bracketed paste mode (DECSET 2004) is currently enabled.
    pub bracketed_paste: bool,
    /// Whether focus reporting (DECSET 1004) is currently enabled.
    pub focus_reporting: bool,
    /// Whether synchronized output (DECSET 2026) is currently enabled.
    pub synchronized_output: bool,
    /// Generation counter incremented on each mode-2026 activation.
    pub sync_output_gen: u64,
    /// Whether OSC 52 clipboard reading queries are permitted.
    pub allow_osc52_read: bool,
    /// Whether OSC 52 clipboard write/clear operations are permitted.
    pub allow_osc52_write: bool,
    /// Internal clipboard content accessible for OSC 52 queries and updates.
    pub clipboard_content: Option<String>,
    /// Pending clipboard updates received via OSC 52: Some(Some(text)) for set, Some(None) for clear.
    pub(crate) pending_clipboard: Option<Option<String>>,
    /// Current working directory reported through OSC 7.
    pub current_dir: Option<PathBuf>,
    /// Shell integration state reported through OSC 133.
    pub shell_integration: Option<ShellIntegrationState>,
    /// Whether color scheme reporting (DECSET 2031) is enabled.
    pub report_color_scheme: bool,
    /// Whether window size notifications (DECSET 2048) are enabled.
    pub report_window_size: bool,
    pub(crate) last_reported_window_size: Option<([usize; 2], [u16; 2])>,
    /// Progress bar status reported through OSC 9;4.
    pub progress: Option<ProgressState>,
    /// Currently active hyperlink ID for incoming text.
    pub active_hyperlink: Option<u32>,
    pub(crate) next_hyperlink_id: u32,
    /// O(1) interning tables for OSC 8 hyperlink URLs. A single `Rc<str>` allocation is shared
    /// between both maps, and `hyperlink_order` tracks FIFO eviction order.
    pub(crate) hyperlinks_by_url: HashMap<Rc<str>, u32>,
    pub(crate) hyperlinks_by_id: HashMap<u32, Rc<str>>,
    pub(crate) hyperlink_order: VecDeque<u32>,
    /// Active flags for the Kitty keyboard protocol.
    pub kitty_keyboard_flags: u8,
    pub kitty_keyboard_stack: Vec<u8>,
    pub(crate) pending_kitty_keyboard: Option<(u8, u8)>,
    // Replies generated by the parser (window size reports) awaiting PTY write-back.
    pub(crate) responses: Vec<Vec<u8>>,
}

#[inline(always)]
fn find_printable_ascii_prefix(bytes: &[u8]) -> usize {
    let mut i = 0;
    while i + 16 <= bytes.len() {
        let chunk0 = u64::from_le_bytes(match bytes[i..i + 8].try_into() {
            Ok(arr) => arr,
            Err(_) => break,
        });
        let chunk1 = u64::from_le_bytes(match bytes[i + 8..i + 16].try_into() {
            Ok(arr) => arr,
            Err(_) => break,
        });
        let lo0 = chunk0.wrapping_sub(0x2020_2020_2020_2020);
        let hi0 = 0x7e7e_7e7e_7e7e_7e7e_u64.wrapping_sub(chunk0);
        let lo1 = chunk1.wrapping_sub(0x2020_2020_2020_2020);
        let hi1 = 0x7e7e_7e7e_7e7e_7e7e_u64.wrapping_sub(chunk1);
        if (((lo0 | hi0) | (lo1 | hi1)) & 0x8080_8080_8080_8080) != 0 {
            for j in 0..16 {
                if !(0x20..=0x7e).contains(&bytes[i + j]) {
                    return i + j;
                }
            }
        }
        i += 16;
    }
    while i + 8 <= bytes.len() {
        let chunk = u64::from_le_bytes(match bytes[i..i + 8].try_into() {
            Ok(arr) => arr,
            Err(_) => break,
        });
        let lo = chunk.wrapping_sub(0x2020_2020_2020_2020);
        let hi = 0x7e7e_7e7e_7e7e_7e7e_u64.wrapping_sub(chunk);
        if ((lo | hi) & 0x8080_8080_8080_8080) != 0 {
            for j in 0..8 {
                if !(0x20..=0x7e).contains(&bytes[i + j]) {
                    return i + j;
                }
            }
        }
        i += 8;
    }
    while i < bytes.len() && (0x20..=0x7e).contains(&bytes[i]) {
        i += 1;
    }
    i
}

impl Terminal {
    #[must_use]
    pub fn new(cols: usize, rows: usize, max_scrollback: usize) -> Self {
        let palette = crate::color::default_256_palette();
        let default_fg = Rgb::new(220, 220, 220);
        let default_bg = Rgb::new(24, 24, 24);
        Self {
            grid: Grid::new(cols, rows, max_scrollback),
            active_fg: Color::DefaultForeground,
            active_bg: Color::DefaultBackground,
            active_underline_color: Color::DefaultForeground,
            active_flags: CellFlags::empty(),
            mouse: MouseState::default(),
            title: String::new(),
            title_dirty: false,
            cell_pixels: [1, 1],
            viewport_pixels: [1, 1],
            default_fg,
            default_bg,
            initial_default_fg: default_fg,
            initial_default_bg: default_bg,
            palette,
            initial_palette: palette,
            palette_dirty: false,
            bracketed_paste: false,
            focus_reporting: false,
            synchronized_output: false,
            sync_output_gen: 0,
            allow_osc52_read: false,
            allow_osc52_write: true,
            clipboard_content: None,
            pending_clipboard: None,
            current_dir: None,
            shell_integration: None,
            report_color_scheme: false,
            report_window_size: false,
            last_reported_window_size: None,
            progress: None,
            active_hyperlink: None,
            next_hyperlink_id: 1,
            hyperlinks_by_url: HashMap::new(),
            hyperlinks_by_id: HashMap::new(),
            hyperlink_order: VecDeque::new(),
            kitty_keyboard_flags: 0,
            kitty_keyboard_stack: Vec::new(),
            pending_kitty_keyboard: None,
            responses: Vec::new(),
        }
    }

    /// Updates the configured default foreground and background colors for OSC queries.
    pub fn set_default_colors(&mut self, fg: Rgb, bg: Rgb) {
        let old_bg = self.default_bg;
        self.default_fg = fg;
        self.default_bg = bg;
        self.initial_default_fg = fg;
        self.initial_default_bg = bg;
        if self.report_color_scheme
            && Self::is_dark_background(old_bg) != Self::is_dark_background(bg)
        {
            self.send_color_scheme_report();
        }
    }

    /// Sets the base 256-color palette and saves it as initial defaults for OSC 104 reset.
    pub fn set_palette(&mut self, palette: [Rgb; 256]) {
        self.palette = palette;
        self.initial_palette = palette;
    }

    pub(crate) fn update_dynamic_background(&mut self, new_bg: Rgb) {
        let old_bg = self.default_bg;
        self.default_bg = new_bg;
        self.palette_dirty = true;
        if self.report_color_scheme
            && Self::is_dark_background(old_bg) != Self::is_dark_background(new_bg)
        {
            self.send_color_scheme_report();
        }
    }

    pub(crate) const fn is_dark_background(bg: Rgb) -> bool {
        (bg.r as u32 * 299 + bg.g as u32 * 587 + bg.b as u32 * 114) / 1000 < 128
    }

    pub(crate) fn send_color_scheme_report(&mut self) {
        let code = if Self::is_dark_background(self.default_bg) {
            1
        } else {
            2
        };
        self.responses
            .push(format!("\x1b[?2031;{}$y", code).into_bytes());
    }

    /// Records the current pixel geometry so clients can size images for this terminal.
    pub fn set_geometry(&mut self, cell_pixels: [u16; 2], viewport_pixels: [u16; 2]) {
        self.cell_pixels = [cell_pixels[0].max(1), cell_pixels[1].max(1)];
        self.viewport_pixels = viewport_pixels;
        if self.report_window_size {
            let current_size = (
                [self.grid.rows, self.grid.cols],
                [self.viewport_pixels[1], self.viewport_pixels[0]],
            );
            if self.last_reported_window_size != Some(current_size) {
                self.last_reported_window_size = Some(current_size);
                self.responses.push(
                    format!(
                        "\x1b[48;{};{};{};{}t",
                        self.grid.rows,
                        self.grid.cols,
                        self.viewport_pixels[1],
                        self.viewport_pixels[0]
                    )
                    .into_bytes(),
                );
            }
        }
    }

    /// Drains replies generated while parsing, for the event loop to write back to the PTY.
    pub fn take_responses(&mut self) -> Vec<Vec<u8>> {
        std::mem::take(&mut self.responses)
    }

    /// Interns a URL into the terminal's hyperlink storage and returns its ID.
    ///
    /// The pool is bounded to [`MAX_HYPERLINKS`]. When capacity is reached, the oldest
    /// entry is evicted via FIFO while preserving unique identifiers for surviving URLs.
    pub fn get_or_intern_hyperlink(&mut self, url: String) -> u32 {
        // Fast path: the URL is already interned (borrow lookup by `&str`).
        if let Some(&id) = self.hyperlinks_by_url.get(url.as_str()) {
            return id;
        }
        if self.hyperlink_order.len() >= MAX_HYPERLINKS
            && let Some(oldest) = self.hyperlink_order.pop_front()
            && let Some(old_url) = self.hyperlinks_by_id.remove(&oldest)
        {
            self.hyperlinks_by_url.remove(old_url.as_ref());
        }
        let id = self.next_hyperlink_id;
        self.next_hyperlink_id = if self.next_hyperlink_id == u32::MAX {
            1
        } else {
            self.next_hyperlink_id + 1
        };
        let url: Rc<str> = Rc::from(url);
        self.hyperlinks_by_url.insert(Rc::clone(&url), id);
        self.hyperlinks_by_id.insert(id, url);
        self.hyperlink_order.push_back(id);
        id
    }

    /// Resolves a hyperlink ID to its underlying URL.
    #[must_use]
    pub fn hyperlink_url(&self, id: u32) -> Option<&str> {
        if id == 0 {
            return None;
        }
        self.hyperlinks_by_id.get(&id).map(Rc::as_ref)
    }

    /// Drains pending clipboard updates received through OSC 52.
    pub fn take_pending_clipboard(&mut self) -> Option<Option<String>> {
        self.pending_clipboard.take()
    }

    /// Drains pending Kitty keyboard mode changes (flags, mode) for event loop synchronization.
    pub fn take_pending_kitty_keyboard(&mut self) -> Option<(u8, u8)> {
        self.pending_kitty_keyboard.take()
    }

    /// Sets the local clipboard content so that OSC 52 queries can return it.
    pub fn set_clipboard_content(&mut self, content: Option<String>) {
        self.clipboard_content = content;
    }

    /// Feeds incoming raw bytes (from PTY) through the provided VT parser.
    #[inline]
    pub fn advance_bytes(&mut self, parser: &mut VtParser, bytes: &[u8]) {
        parser.advance_bytes(self, bytes);
    }
}

/// Stateful VT escape sequence parser paired with terminal-facing escape state.
///
/// Owns the underlying [`vte::Parser`] and keeps parsing state strictly coupled with
/// escape-in-progress detection, preventing desynchronization across chunk boundaries.
#[derive(Default)]
pub struct VtParser {
    pub(crate) parser: Parser,
    pub(crate) in_escape: bool,
}

impl VtParser {
    #[must_use]
    pub fn new() -> Self {
        Self {
            parser: Parser::new(),
            in_escape: false,
        }
    }

    /// Resets parser state to Ground, clearing any partial escape sequences.
    pub fn reset(&mut self) {
        self.parser = Parser::new();
        self.in_escape = false;
    }

    /// Returns `true` if the parser is currently within an incomplete escape sequence.
    #[must_use]
    pub fn is_in_escape(&self) -> bool {
        self.in_escape
    }

    /// Feeds incoming raw bytes through the parser into the target terminal.
    pub fn advance_bytes(&mut self, terminal: &mut Terminal, bytes: &[u8]) {
        let mut idx = 0;
        while idx < bytes.len() {
            if self.in_escape {
                while idx < bytes.len() && self.in_escape {
                    let mut performer = Performer {
                        terminal,
                        in_escape: &mut self.in_escape,
                    };
                    self.parser.advance(&mut performer, &bytes[idx..=idx]);
                    idx += 1;
                }
                continue;
            }

            let remaining = &bytes[idx..];
            let special_pos =
                memchr::memchr3(b'\x1b', b'\n', b'\r', remaining).unwrap_or(remaining.len());

            if special_pos > 0 {
                let printable_len = find_printable_ascii_prefix(&remaining[..special_pos]);
                if printable_len > 0 {
                    terminal.grid.write_ascii_run(
                        &remaining[..printable_len],
                        terminal.active_fg,
                        terminal.active_bg,
                        terminal.active_flags,
                        terminal.active_underline_color,
                        terminal.active_hyperlink,
                    );
                    idx += printable_len;
                    continue;
                }

                // If non-ASCII bytes precede the special characters or printable ASCII,
                // chunk them together and pass to the parser directly without 1-byte thrashing.
                let chunk_len = remaining[..special_pos]
                    .iter()
                    .position(|&b| (0x20..=0x7e).contains(&b))
                    .unwrap_or(special_pos);

                let chunk = &remaining[..chunk_len];
                if (0x90..=0x9F).contains(&chunk[0]) {
                    self.in_escape = true;
                }
                let mut performer = Performer {
                    terminal,
                    in_escape: &mut self.in_escape,
                };
                self.parser.advance(&mut performer, chunk);
                idx += chunk_len;
                continue;
            }

            match remaining[0] {
                b'\n' | 0x0B | 0x0C => {
                    terminal.grid.newline();
                    terminal.grid.carriage_return();
                    idx += 1;
                }
                b'\r' => {
                    terminal.grid.carriage_return();
                    idx += 1;
                }
                b'\t' => {
                    terminal.grid.tab();
                    idx += 1;
                }
                b'\x08' => {
                    terminal.grid.backspace();
                    idx += 1;
                }
                b'\x07' => {
                    idx += 1;
                }
                b'\x1b' => {
                    self.in_escape = true;
                    // Check if remaining slice starts with CSI ("\x1b[") and find its terminator (0x40..=0x7E)
                    if remaining.len() >= 2
                        && remaining[1] == b'['
                        && let Some(final_idx) = remaining[2..]
                            .iter()
                            .position(|&b| (0x40..=0x7e).contains(&b))
                    {
                        let end = 2 + final_idx;
                        let mut performer = Performer {
                            terminal,
                            in_escape: &mut self.in_escape,
                        };
                        self.parser.advance(&mut performer, &remaining[..=end]);
                        idx += end + 1;
                        continue;
                    }
                    let mut performer = Performer {
                        terminal,
                        in_escape: &mut self.in_escape,
                    };
                    self.parser.advance(&mut performer, &remaining[..1]);
                    idx += 1;
                }
                byte => {
                    if (0x90..=0x9F).contains(&byte) {
                        self.in_escape = true;
                    }
                    let mut performer = Performer {
                        terminal,
                        in_escape: &mut self.in_escape,
                    };
                    self.parser.advance(&mut performer, &remaining[..1]);
                    idx += 1;
                }
            }
        }
    }
}

struct Performer<'a> {
    terminal: &'a mut Terminal,
    in_escape: &'a mut bool,
}

impl Perform for Performer<'_> {
    #[inline]
    fn print(&mut self, c: char) {
        *self.in_escape = false;
        self.terminal.print(c);
    }

    #[inline]
    fn execute(&mut self, byte: u8) {
        *self.in_escape = false;
        self.terminal.execute(byte);
    }

    #[inline]
    fn hook(&mut self, params: &Params, intermediates: &[u8], ignore: bool, action: char) {
        *self.in_escape = true;
        self.terminal.hook(params, intermediates, ignore, action);
    }

    #[inline]
    fn put(&mut self, byte: u8) {
        *self.in_escape = true;
        self.terminal.put(byte);
    }

    #[inline]
    fn unhook(&mut self) {
        *self.in_escape = false;
        self.terminal.unhook();
    }

    #[inline]
    fn osc_dispatch(&mut self, params: &[&[u8]], bell_terminated: bool) {
        *self.in_escape = false;
        self.terminal.osc_dispatch(params, bell_terminated);
    }

    #[inline]
    fn csi_dispatch(&mut self, params: &Params, intermediates: &[u8], ignore: bool, action: char) {
        *self.in_escape = false;
        self.terminal
            .csi_dispatch(params, intermediates, ignore, action);
    }

    #[inline]
    fn esc_dispatch(&mut self, intermediates: &[u8], ignore: bool, byte: u8) {
        *self.in_escape = false;
        self.terminal.esc_dispatch(intermediates, ignore, byte);
    }
}

impl Perform for Terminal {
    #[inline]
    fn print(&mut self, c: char) {
        self.grid.write_char_styled(
            c,
            self.active_fg,
            self.active_bg,
            self.active_flags,
            self.active_underline_color,
            self.active_hyperlink,
        );
    }

    fn execute(&mut self, byte: u8) {
        match byte {
            b'\n' | 0x0B | 0x0C => {
                self.grid.newline();
                self.grid.carriage_return();
            }
            b'\r' => self.grid.carriage_return(),
            b'\x08' => self.grid.backspace(),
            b'\t' => self.grid.tab(),
            b'\x07' => {} // Bell
            _ => {}
        }
    }

    fn hook(&mut self, _params: &Params, _intermediates: &[u8], _ignore: bool, _action: char) {}

    fn put(&mut self, _byte: u8) {}

    fn unhook(&mut self) {}

    fn osc_dispatch(&mut self, params: &[&[u8]], bell_terminated: bool) {
        self.handle_osc(params, bell_terminated);
    }

    fn csi_dispatch(&mut self, params: &Params, intermediates: &[u8], ignore: bool, action: char) {
        self.handle_csi(params, intermediates, ignore, action);
    }

    fn esc_dispatch(&mut self, _intermediates: &[u8], _ignore: bool, byte: u8) {
        match byte {
            b'7' => self.grid.save_cursor(),
            b'8' => self.grid.restore_cursor(),
            b'M' => {
                // Reverse Index
                if self.grid.cursor.row == self.grid.scroll_region_top {
                    self.grid.scroll_down(1);
                } else {
                    self.grid.cursor.row = self.grid.cursor.row.saturating_sub(1);
                }
            }
            b'c' => {
                // Full Reset (RIS)
                self.grid.clear_screen(ClearMode::All);
                self.grid.cursor = crate::grid::Cursor::default();
                self.mouse = MouseState::default();
                self.bracketed_paste = false;
                self.focus_reporting = false;
                self.synchronized_output = false;
                self.current_dir = None;
                self.shell_integration = None;
                self.report_color_scheme = false;
                self.report_window_size = false;
                self.progress = None;
                self.active_hyperlink = None;
                self.grid.clear_all_hyperlinks();
                self.grid.prompt_marks.clear();
                self.hyperlinks_by_url.clear();
                self.hyperlinks_by_id.clear();
                self.hyperlink_order.clear();
                self.title.clear();
                self.title_dirty = true;
                self.default_fg = self.initial_default_fg;
                self.default_bg = self.initial_default_bg;
                self.palette = self.initial_palette;
                self.palette_dirty = true;
                self.next_hyperlink_id = 1;
                self.kitty_keyboard_flags = 0;
                self.kitty_keyboard_stack.clear();
                self.pending_kitty_keyboard = Some((0, 1));
                self.reset_attributes();
            }
            _ => {}
        }
    }
}
