//! ANSI / VT escape sequence parser implementing the DEC terminal state machine.

pub(crate) mod csi;
pub(crate) mod osc;
pub(crate) mod sgr;

#[cfg(test)]
mod tests;

use std::path::PathBuf;

use vte::{Params, Parser, Perform};

use crate::color::{Color, Rgb};
use crate::grid::{CellFlags, ClearMode, Grid};
use crate::input::mouse::MouseState;

pub(crate) const MAX_HYPERLINKS: usize = 1024;

/// Semantic shell integration state reported through OSC 133.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShellIntegrationState {
    PromptStart,
    CommandStart,
    OutputStart,
    CommandFinished(Option<i32>),
}

/// Progress bar notification state (OSC 9;4).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProgressState {
    Normal(u8),
    Error(u8),
    Indeterminate,
    Warning(u8),
}

/// Terminal emulation state machine combining a screen grid, current formatting attributes,
/// and a VT parser.
pub struct Terminal {
    pub grid: Grid,
    pub active_fg: Color,
    pub active_bg: Color,
    pub active_underline_color: Color,
    pub active_flags: CellFlags,
    pub mouse: MouseState,
    pub title: String,
    /// Cell size in physical pixels, reported back through `CSI 16 t`.
    pub cell_pixels: [u16; 2],
    /// Text-area size in physical pixels, reported back through `CSI 14 t`.
    pub viewport_pixels: [u16; 2],
    pub default_fg: Rgb,
    pub default_bg: Rgb,
    pub initial_default_fg: Rgb,
    pub initial_default_bg: Rgb,
    pub palette: [Rgb; 256],
    pub initial_palette: [Rgb; 256],
    pub palette_dirty: bool,
    /// Whether bracketed paste mode (DECSET 2004) is currently enabled.
    pub bracketed_paste: bool,
    /// Whether focus reporting (DECSET 1004) is currently enabled.
    pub focus_reporting: bool,
    /// Whether synchronized output (DECSET 2026) is currently enabled.
    pub synchronized_output: bool,
    /// Generation counter incremented on each mode-2026 activation.
    pub sync_output_gen: u64,
    /// Internal clipboard content accessible for OSC 52 queries and updates.
    pub clipboard_content: Option<String>,
    /// Pending clipboard updates received via OSC 52: Some(Some(text)) for set, Some(None) for clear.
    pub(crate) pending_clipboard: Option<Option<String>>,
    /// Current working directory reported through OSC 7.
    pub current_dir: Option<PathBuf>,
    /// Shell integration state reported through OSC 133.
    pub shell_integration: Option<ShellIntegrationState>,
    /// Whether color scheme reporting (DECSET 2031) is enabled.
    pub report_color_scheme: bool,
    /// Whether window size notifications (DECSET 2048) are enabled.
    pub report_window_size: bool,
    pub(crate) last_reported_window_size: Option<([usize; 2], [u16; 2])>,
    /// Progress bar status reported through OSC 9;4.
    pub progress: Option<ProgressState>,
    /// Currently active hyperlink ID for incoming text.
    pub active_hyperlink: Option<u32>,
    pub(crate) next_hyperlink_id: u32,
    pub(crate) hyperlink_pool: Vec<(u32, String)>,
    /// Active flags for the Kitty keyboard protocol.
    pub kitty_keyboard_flags: u8,
    pub kitty_keyboard_stack: Vec<u8>,
    pub(crate) pending_kitty_keyboard: Option<(u8, u8)>,
    // Replies generated by the parser (window size reports) awaiting PTY write-back.
    pub(crate) responses: Vec<Vec<u8>>,
    pub(crate) parser_in_escape: bool,
    parser: Option<Parser>,
}

#[inline(always)]
fn find_printable_ascii_prefix(bytes: &[u8]) -> usize {
    let mut i = 0;
    while i + 8 <= bytes.len() {
        let chunk = u64::from_le_bytes(match bytes[i..i + 8].try_into() {
            Ok(arr) => arr,
            Err(_) => break,
        });
        let lo = chunk.wrapping_sub(0x2020_2020_2020_2020);
        let hi = 0x7e7e_7e7e_7e7e_7e7e_u64.wrapping_sub(chunk);
        if ((lo | hi) & 0x8080_8080_8080_8080) != 0 {
            for j in 0..8 {
                if !(0x20..=0x7e).contains(&bytes[i + j]) {
                    return i + j;
                }
            }
        }
        i += 8;
    }
    while i < bytes.len() && (0x20..=0x7e).contains(&bytes[i]) {
        i += 1;
    }
    i
}

impl Terminal {
    #[must_use]
    pub fn new(cols: usize, rows: usize, max_scrollback: usize) -> Self {
        let palette = crate::color::default_256_palette();
        let default_fg = Rgb::new(220, 220, 220);
        let default_bg = Rgb::new(24, 24, 24);
        Self {
            grid: Grid::new(cols, rows, max_scrollback),
            active_fg: Color::DefaultForeground,
            active_bg: Color::DefaultBackground,
            active_underline_color: Color::DefaultForeground,
            active_flags: CellFlags::empty(),
            mouse: MouseState::default(),
            title: String::new(),
            cell_pixels: [1, 1],
            viewport_pixels: [1, 1],
            default_fg,
            default_bg,
            initial_default_fg: default_fg,
            initial_default_bg: default_bg,
            palette,
            initial_palette: palette,
            palette_dirty: false,
            bracketed_paste: false,
            focus_reporting: false,
            synchronized_output: false,
            sync_output_gen: 0,
            clipboard_content: None,
            pending_clipboard: None,
            current_dir: None,
            shell_integration: None,
            report_color_scheme: false,
            report_window_size: false,
            last_reported_window_size: None,
            progress: None,
            active_hyperlink: None,
            next_hyperlink_id: 1,
            hyperlink_pool: Vec::new(),
            kitty_keyboard_flags: 0,
            kitty_keyboard_stack: Vec::new(),
            pending_kitty_keyboard: None,
            responses: Vec::new(),
            parser_in_escape: false,
            parser: Some(Parser::new()),
        }
    }

    /// Updates the configured default foreground and background colors for OSC queries.
    pub fn set_default_colors(&mut self, fg: Rgb, bg: Rgb) {
        let old_bg = self.default_bg;
        self.default_fg = fg;
        self.default_bg = bg;
        self.initial_default_fg = fg;
        self.initial_default_bg = bg;
        if self.report_color_scheme
            && Self::is_dark_background(old_bg) != Self::is_dark_background(bg)
        {
            self.send_color_scheme_report();
        }
    }

    /// Sets the base 256-color palette and saves it as initial defaults for OSC 104 reset.
    pub fn set_palette(&mut self, palette: [Rgb; 256]) {
        self.palette = palette;
        self.initial_palette = palette;
    }

    pub(crate) const fn is_dark_background(bg: Rgb) -> bool {
        (bg.r as u32 * 299 + bg.g as u32 * 587 + bg.b as u32 * 114) / 1000 < 128
    }

    pub(crate) fn send_color_scheme_report(&mut self) {
        let code = if Self::is_dark_background(self.default_bg) {
            1
        } else {
            2
        };
        self.responses
            .push(format!("\x1b[?2031;{}$y", code).into_bytes());
    }

    /// Records the current pixel geometry so clients can size images for this terminal.
    pub fn set_geometry(&mut self, cell_pixels: [u16; 2], viewport_pixels: [u16; 2]) {
        self.cell_pixels = [cell_pixels[0].max(1), cell_pixels[1].max(1)];
        self.viewport_pixels = viewport_pixels;
        if self.report_window_size {
            let current_size = (
                [self.grid.rows, self.grid.cols],
                [self.viewport_pixels[1], self.viewport_pixels[0]],
            );
            if self.last_reported_window_size != Some(current_size) {
                self.last_reported_window_size = Some(current_size);
                self.responses.push(
                    format!(
                        "\x1b[48;{};{};{};{}t",
                        self.grid.rows,
                        self.grid.cols,
                        self.viewport_pixels[1],
                        self.viewport_pixels[0]
                    )
                    .into_bytes(),
                );
            }
        }
    }

    /// Drains replies generated while parsing, for the event loop to write back to the PTY.
    pub fn take_responses(&mut self) -> Vec<Vec<u8>> {
        std::mem::take(&mut self.responses)
    }

    /// Interns a URL into the terminal's hyperlink storage and returns its ID.
    ///
    /// The pool is bounded to [`MAX_HYPERLINKS`]. When capacity is reached, the oldest
    /// entry is evicted via FIFO while preserving unique identifiers for surviving URLs.
    pub fn get_or_intern_hyperlink(&mut self, url: String) -> u32 {
        if let Some((id, _)) = self.hyperlink_pool.iter().find(|(_, u)| u == &url) {
            *id
        } else {
            if self.hyperlink_pool.len() >= MAX_HYPERLINKS {
                self.hyperlink_pool.remove(0);
            }
            let id = self.next_hyperlink_id;
            self.next_hyperlink_id = if self.next_hyperlink_id == u32::MAX {
                1
            } else {
                self.next_hyperlink_id + 1
            };
            self.hyperlink_pool.push((id, url));
            id
        }
    }

    /// Resolves a hyperlink ID to its underlying URL.
    #[must_use]
    pub fn hyperlink_url(&self, id: u32) -> Option<&str> {
        if id == 0 {
            return None;
        }
        self.hyperlink_pool
            .iter()
            .find(|(i, _)| *i == id)
            .map(|(_, u)| u.as_str())
    }

    /// Drains pending clipboard updates received through OSC 52.
    pub fn take_pending_clipboard(&mut self) -> Option<Option<String>> {
        self.pending_clipboard.take()
    }

    /// Drains pending Kitty keyboard mode changes (flags, mode) for event loop synchronization.
    pub fn take_pending_kitty_keyboard(&mut self) -> Option<(u8, u8)> {
        self.pending_kitty_keyboard.take()
    }

    /// Sets the local clipboard content so that OSC 52 queries can return it.
    pub fn set_clipboard_content(&mut self, content: Option<String>) {
        self.clipboard_content = content;
    }

    /// Feeds incoming raw bytes (from PTY) through the VT parser.
    pub fn advance_bytes(&mut self, bytes: &[u8]) {
        let mut idx = 0;
        while idx < bytes.len() {
            if self.parser_in_escape {
                let mut parser = self.parser.take().unwrap_or_default();
                while idx < bytes.len() && self.parser_in_escape {
                    parser.advance(self, &bytes[idx..=idx]);
                    idx += 1;
                }
                self.parser = Some(parser);
                continue;
            }

            let remaining = &bytes[idx..];
            let special_pos =
                memchr::memchr3(b'\x1b', b'\n', b'\r', remaining).unwrap_or(remaining.len());

            if special_pos > 0 {
                let printable_len = find_printable_ascii_prefix(&remaining[..special_pos]);
                if printable_len > 0 {
                    self.grid.write_ascii_run(
                        &remaining[..printable_len],
                        self.active_fg,
                        self.active_bg,
                        self.active_flags,
                        self.active_underline_color,
                        self.active_hyperlink,
                    );
                    idx += printable_len;
                    continue;
                }

                let byte = remaining[0];
                if (0x90..=0x9F).contains(&byte) {
                    self.parser_in_escape = true;
                }
                let mut parser = self.parser.take().unwrap_or_default();
                parser.advance(self, &remaining[..1]);
                self.parser = Some(parser);
                idx += 1;
                continue;
            }

            match remaining[0] {
                b'\n' | 0x0B | 0x0C => {
                    self.grid.newline();
                    self.grid.carriage_return();
                    idx += 1;
                }
                b'\r' => {
                    self.grid.carriage_return();
                    idx += 1;
                }
                b'\t' => {
                    self.grid.tab();
                    idx += 1;
                }
                b'\x08' => {
                    self.grid.backspace();
                    idx += 1;
                }
                b'\x07' => {
                    idx += 1;
                }
                b'\x1b' => {
                    self.parser_in_escape = true;
                    let mut parser = self.parser.take().unwrap_or_default();
                    parser.advance(self, &remaining[..1]);
                    self.parser = Some(parser);
                    idx += 1;
                }
                byte => {
                    if (0x90..=0x9F).contains(&byte) {
                        self.parser_in_escape = true;
                    }
                    let mut parser = self.parser.take().unwrap_or_default();
                    parser.advance(self, &remaining[..1]);
                    self.parser = Some(parser);
                    idx += 1;
                }
            }
        }
    }
}

impl Perform for Terminal {
    #[inline]
    fn print(&mut self, c: char) {
        self.parser_in_escape = false;
        self.grid.write_char_styled(
            c,
            self.active_fg,
            self.active_bg,
            self.active_flags,
            self.active_underline_color,
            self.active_hyperlink,
        );
    }

    fn execute(&mut self, byte: u8) {
        self.parser_in_escape = false;
        match byte {
            b'\n' | 0x0B | 0x0C => {
                self.grid.newline();
                self.grid.carriage_return();
            }
            b'\r' => self.grid.carriage_return(),
            b'\x08' => self.grid.backspace(),
            b'\t' => self.grid.tab(),
            b'\x07' => {} // Bell
            _ => {}
        }
    }

    fn hook(&mut self, _params: &Params, _intermediates: &[u8], _ignore: bool, _action: char) {
        self.parser_in_escape = true;
    }

    fn put(&mut self, _byte: u8) {}

    fn unhook(&mut self) {
        self.parser_in_escape = false;
    }

    fn osc_dispatch(&mut self, params: &[&[u8]], bell_terminated: bool) {
        self.parser_in_escape = false;
        self.handle_osc(params, bell_terminated);
    }

    fn csi_dispatch(&mut self, params: &Params, intermediates: &[u8], ignore: bool, action: char) {
        self.parser_in_escape = false;
        self.handle_csi(params, intermediates, ignore, action);
    }

    fn esc_dispatch(&mut self, _intermediates: &[u8], _ignore: bool, byte: u8) {
        self.parser_in_escape = false;
        match byte {
            b'7' => self.grid.save_cursor(),
            b'8' => self.grid.restore_cursor(),
            b'M' => {
                // Reverse Index
                if self.grid.cursor.row == self.grid.scroll_region_top {
                    self.grid.scroll_down(1);
                } else {
                    self.grid.cursor.row = self.grid.cursor.row.saturating_sub(1);
                }
            }
            b'c' => {
                // Full Reset (RIS)
                self.grid.clear_screen(ClearMode::All);
                self.grid.cursor = crate::grid::Cursor::default();
                self.mouse = MouseState::default();
                self.bracketed_paste = false;
                self.focus_reporting = false;
                self.synchronized_output = false;
                self.current_dir = None;
                self.shell_integration = None;
                self.report_color_scheme = false;
                self.report_window_size = false;
                self.progress = None;
                self.active_hyperlink = None;
                self.grid.clear_all_hyperlinks();
                self.grid.prompt_marks.clear();
                self.hyperlink_pool.clear();
                self.default_fg = self.initial_default_fg;
                self.default_bg = self.initial_default_bg;
                self.palette = self.initial_palette;
                self.palette_dirty = true;
                self.next_hyperlink_id = 1;
                self.kitty_keyboard_flags = 0;
                self.kitty_keyboard_stack.clear();
                self.pending_kitty_keyboard = Some((0, 1));
                self.reset_attributes();
            }
            _ => {}
        }
    }
}
