//! ANSI / VT escape sequence parser implementing the DEC terminal state machine.

use crate::color::{Color, Rgb};
use crate::grid::{CellFlags, ClearMode, Grid};
use crate::input::mouse::MouseState;
use base64::Engine;
use base64::prelude::BASE64_STANDARD;
use std::collections::{HashMap, VecDeque};
use std::path::PathBuf;
use std::rc::Rc;
use vte::{Params, Perform};

pub use vte::Parser;

#[doc(hidden)]
pub const MAX_HYPERLINKS: usize = 1024;

/// Semantic shell integration state reported through OSC 133.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShellIntegrationState {
    PromptStart,
    CommandStart,
    OutputStart,
    CommandFinished(Option<i32>),
}

/// Progress bar notification state (OSC 9;4).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProgressState {
    Normal(u8),
    Error(u8),
    Indeterminate,
    Warning(u8),
}

/// Terminal emulation state machine combining a screen grid, current formatting attributes,
/// and a VT parser.
pub struct Terminal {
    pub grid: Grid,
    pub active_fg: Color,
    pub active_bg: Color,
    pub active_underline_color: Color,
    pub active_flags: CellFlags,
    pub mouse: MouseState,
    pub title: String,
    pub title_dirty: bool,
    /// Cell size in physical pixels, reported back through `CSI 16 t`.
    pub cell_pixels: [u16; 2],
    /// Text-area size in physical pixels, reported back through `CSI 14 t`.
    pub viewport_pixels: [u16; 2],
    pub default_fg: Rgb,
    pub default_bg: Rgb,
    pub initial_default_fg: Rgb,
    pub initial_default_bg: Rgb,
    pub palette: [Rgb; 256],
    pub initial_palette: [Rgb; 256],
    pub palette_dirty: bool,
    /// Whether bracketed paste mode (DECSET 2004) is currently enabled.
    pub bracketed_paste: bool,
    /// Whether focus reporting (DECSET 1004) is currently enabled.
    pub focus_reporting: bool,
    /// Whether synchronized output (DECSET 2026) is currently enabled.
    pub synchronized_output: bool,
    /// Generation counter incremented on each mode-2026 activation.
    pub sync_output_gen: u64,
    /// Whether OSC 52 clipboard reading queries are permitted.
    pub allow_osc52_read: bool,
    /// Whether OSC 52 clipboard write/clear operations are permitted.
    pub allow_osc52_write: bool,
    /// Internal clipboard content accessible for OSC 52 queries and updates.
    pub clipboard_content: Option<String>,
    /// Pending clipboard updates received via OSC 52: Some(Some(text)) for set, Some(None) for clear.
    pub(crate) pending_clipboard: Option<Option<String>>,
    /// Current working directory reported through OSC 7.
    pub current_dir: Option<PathBuf>,
    /// Shell integration state reported through OSC 133.
    pub shell_integration: Option<ShellIntegrationState>,
    /// Whether color scheme reporting (DECSET 2031) is enabled.
    pub report_color_scheme: bool,
    /// Whether window size notifications (DECSET 2048) are enabled.
    pub report_window_size: bool,
    pub(crate) last_reported_window_size: Option<([usize; 2], [u16; 2])>,
    /// Progress bar status reported through OSC 9;4.
    pub progress: Option<ProgressState>,
    /// Currently active hyperlink ID for incoming text.
    pub active_hyperlink: Option<u32>,
    pub(crate) next_hyperlink_id: u32,
    /// O(1) interning tables for OSC 8 hyperlink URLs. A single `Rc<str>` allocation is shared
    /// between both maps, and `hyperlink_order` tracks FIFO eviction order.
    #[doc(hidden)]
    pub hyperlinks_by_url: HashMap<Rc<str>, u32>,
    #[doc(hidden)]
    pub hyperlinks_by_id: HashMap<u32, Rc<str>>,
    #[doc(hidden)]
    pub hyperlink_order: VecDeque<u32>,
    /// Active flags for the Kitty keyboard protocol.
    pub kitty_keyboard_flags: u8,
    pub kitty_keyboard_stack: Vec<u8>,
    pub(crate) pending_kitty_keyboard: Option<(u8, u8)>,
    // Replies generated by the parser (window size reports) awaiting PTY write-back.
    pub(crate) responses: Vec<Vec<u8>>,
}

#[inline(always)]
fn find_printable_ascii_prefix(bytes: &[u8]) -> usize {
    let mut i = 0;
    while i + 16 <= bytes.len() {
        let chunk0 = u64::from_le_bytes(match bytes[i..i + 8].try_into() {
            Ok(arr) => arr,
            Err(_) => break,
        });
        let chunk1 = u64::from_le_bytes(match bytes[i + 8..i + 16].try_into() {
            Ok(arr) => arr,
            Err(_) => break,
        });
        let lo0 = chunk0.wrapping_sub(0x2020_2020_2020_2020);
        let hi0 = 0x7e7e_7e7e_7e7e_7e7e_u64.wrapping_sub(chunk0);
        let lo1 = chunk1.wrapping_sub(0x2020_2020_2020_2020);
        let hi1 = 0x7e7e_7e7e_7e7e_7e7e_u64.wrapping_sub(chunk1);
        if (((lo0 | hi0) | (lo1 | hi1)) & 0x8080_8080_8080_8080) != 0 {
            for j in 0..16 {
                if !(0x20..=0x7e).contains(&bytes[i + j]) {
                    return i + j;
                }
            }
        }
        i += 16;
    }
    while i + 8 <= bytes.len() {
        let chunk = u64::from_le_bytes(match bytes[i..i + 8].try_into() {
            Ok(arr) => arr,
            Err(_) => break,
        });
        let lo = chunk.wrapping_sub(0x2020_2020_2020_2020);
        let hi = 0x7e7e_7e7e_7e7e_7e7e_u64.wrapping_sub(chunk);
        if ((lo | hi) & 0x8080_8080_8080_8080) != 0 {
            for j in 0..8 {
                if !(0x20..=0x7e).contains(&bytes[i + j]) {
                    return i + j;
                }
            }
        }
        i += 8;
    }
    while i < bytes.len() && (0x20..=0x7e).contains(&bytes[i]) {
        i += 1;
    }
    i
}

impl Terminal {
    #[must_use]
    pub fn new(cols: usize, rows: usize, max_scrollback: usize) -> Self {
        let palette = crate::color::default_256_palette();
        let default_fg = Rgb::new(220, 220, 220);
        let default_bg = Rgb::new(24, 24, 24);
        Self {
            grid: Grid::new(cols, rows, max_scrollback),
            active_fg: Color::DefaultForeground,
            active_bg: Color::DefaultBackground,
            active_underline_color: Color::DefaultForeground,
            active_flags: CellFlags::empty(),
            mouse: MouseState::default(),
            title: String::new(),
            title_dirty: false,
            cell_pixels: [1, 1],
            viewport_pixels: [1, 1],
            default_fg,
            default_bg,
            initial_default_fg: default_fg,
            initial_default_bg: default_bg,
            palette,
            initial_palette: palette,
            palette_dirty: false,
            bracketed_paste: false,
            focus_reporting: false,
            synchronized_output: false,
            sync_output_gen: 0,
            allow_osc52_read: false,
            allow_osc52_write: true,
            clipboard_content: None,
            pending_clipboard: None,
            current_dir: None,
            shell_integration: None,
            report_color_scheme: false,
            report_window_size: false,
            last_reported_window_size: None,
            progress: None,
            active_hyperlink: None,
            next_hyperlink_id: 1,
            hyperlinks_by_url: HashMap::new(),
            hyperlinks_by_id: HashMap::new(),
            hyperlink_order: VecDeque::new(),
            kitty_keyboard_flags: 0,
            kitty_keyboard_stack: Vec::new(),
            pending_kitty_keyboard: None,
            responses: Vec::new(),
        }
    }

    /// Updates the configured default foreground and background colors for OSC queries.
    pub fn set_default_colors(&mut self, fg: Rgb, bg: Rgb) {
        let old_bg = self.default_bg;
        self.default_fg = fg;
        self.default_bg = bg;
        self.initial_default_fg = fg;
        self.initial_default_bg = bg;
        if self.report_color_scheme
            && Self::is_dark_background(old_bg) != Self::is_dark_background(bg)
        {
            self.send_color_scheme_report();
        }
    }

    /// Sets the base 256-color palette and saves it as initial defaults for OSC 104 reset.
    pub fn set_palette(&mut self, palette: [Rgb; 256]) {
        self.palette = palette;
        self.initial_palette = palette;
    }

    pub(crate) fn update_dynamic_background(&mut self, new_bg: Rgb) {
        let old_bg = self.default_bg;
        self.default_bg = new_bg;
        self.palette_dirty = true;
        if self.report_color_scheme
            && Self::is_dark_background(old_bg) != Self::is_dark_background(new_bg)
        {
            self.send_color_scheme_report();
        }
    }

    pub(crate) const fn is_dark_background(bg: Rgb) -> bool {
        (bg.r as u32 * 299 + bg.g as u32 * 587 + bg.b as u32 * 114) / 1000 < 128
    }

    pub(crate) fn send_color_scheme_report(&mut self) {
        let code = if Self::is_dark_background(self.default_bg) {
            1
        } else {
            2
        };
        self.responses
            .push(format!("\x1b[?2031;{}$y", code).into_bytes());
    }

    /// Records the current pixel geometry so clients can size images for this terminal.
    pub fn set_geometry(&mut self, cell_pixels: [u16; 2], viewport_pixels: [u16; 2]) {
        self.cell_pixels = [cell_pixels[0].max(1), cell_pixels[1].max(1)];
        self.viewport_pixels = viewport_pixels;
        if self.report_window_size {
            let current_size = (
                [self.grid.rows, self.grid.cols],
                [self.viewport_pixels[1], self.viewport_pixels[0]],
            );
            if self.last_reported_window_size != Some(current_size) {
                self.last_reported_window_size = Some(current_size);
                self.responses.push(
                    format!(
                        "\x1b[48;{};{};{};{}t",
                        self.grid.rows,
                        self.grid.cols,
                        self.viewport_pixels[1],
                        self.viewport_pixels[0]
                    )
                    .into_bytes(),
                );
            }
        }
    }

    /// Drains replies generated while parsing, for the event loop to write back to the PTY.
    pub fn take_responses(&mut self) -> Vec<Vec<u8>> {
        std::mem::take(&mut self.responses)
    }

    /// Interns a URL into the terminal's hyperlink storage and returns its ID.
    ///
    /// The pool is bounded to [`MAX_HYPERLINKS`]. When capacity is reached, the oldest
    /// entry is evicted via FIFO while preserving unique identifiers for surviving URLs.
    pub fn get_or_intern_hyperlink(&mut self, url: String) -> u32 {
        // Fast path: the URL is already interned (borrow lookup by `&str`).
        if let Some(&id) = self.hyperlinks_by_url.get(url.as_str()) {
            return id;
        }
        if self.hyperlink_order.len() >= MAX_HYPERLINKS
            && let Some(oldest) = self.hyperlink_order.pop_front()
            && let Some(old_url) = self.hyperlinks_by_id.remove(&oldest)
        {
            self.hyperlinks_by_url.remove(old_url.as_ref());
        }
        let id = self.next_hyperlink_id;
        self.next_hyperlink_id = if self.next_hyperlink_id == u32::MAX {
            1
        } else {
            self.next_hyperlink_id + 1
        };
        let url: Rc<str> = Rc::from(url);
        self.hyperlinks_by_url.insert(Rc::clone(&url), id);
        self.hyperlinks_by_id.insert(id, url);
        self.hyperlink_order.push_back(id);
        id
    }

    /// Resolves a hyperlink ID to its underlying URL.
    #[must_use]
    pub fn hyperlink_url(&self, id: u32) -> Option<&str> {
        if id == 0 {
            return None;
        }
        self.hyperlinks_by_id.get(&id).map(Rc::as_ref)
    }

    /// Drains pending clipboard updates received through OSC 52.
    pub fn take_pending_clipboard(&mut self) -> Option<Option<String>> {
        self.pending_clipboard.take()
    }

    /// Drains pending Kitty keyboard mode changes (flags, mode) for event loop synchronization.
    pub fn take_pending_kitty_keyboard(&mut self) -> Option<(u8, u8)> {
        self.pending_kitty_keyboard.take()
    }

    /// Sets the local clipboard content so that OSC 52 queries can return it.
    pub fn set_clipboard_content(&mut self, content: Option<String>) {
        self.clipboard_content = content;
    }

    /// Feeds incoming raw bytes (from PTY) through the provided VT parser.
    #[inline]
    pub fn advance_bytes(&mut self, parser: &mut VtParser, bytes: &[u8]) {
        parser.advance_bytes(self, bytes);
    }
}

/// Stateful VT escape sequence parser paired with terminal-facing escape state.
///
/// Owns the underlying [`vte::Parser`] and keeps parsing state strictly coupled with
/// escape-in-progress detection, preventing desynchronization across chunk boundaries.
#[derive(Default)]
pub struct VtParser {
    pub(crate) parser: Parser,
    pub(crate) in_escape: bool,
}

impl VtParser {
    #[must_use]
    pub fn new() -> Self {
        Self {
            parser: Parser::new(),
            in_escape: false,
        }
    }

    /// Resets parser state to Ground, clearing any partial escape sequences.
    pub fn reset(&mut self) {
        self.parser = Parser::new();
        self.in_escape = false;
    }

    /// Returns `true` if the parser is currently within an incomplete escape sequence.
    #[must_use]
    pub fn is_in_escape(&self) -> bool {
        self.in_escape
    }

    /// Feeds incoming raw bytes through the parser into the target terminal.
    pub fn advance_bytes(&mut self, terminal: &mut Terminal, bytes: &[u8]) {
        let mut idx = 0;
        while idx < bytes.len() {
            if self.in_escape {
                while idx < bytes.len() && self.in_escape {
                    let mut performer = Performer {
                        terminal,
                        in_escape: &mut self.in_escape,
                    };
                    self.parser.advance(&mut performer, &bytes[idx..=idx]);
                    idx += 1;
                }
                continue;
            }

            let remaining = &bytes[idx..];
            let special_pos =
                memchr::memchr3(b'\x1b', b'\n', b'\r', remaining).unwrap_or(remaining.len());

            if special_pos > 0 {
                let printable_len = find_printable_ascii_prefix(&remaining[..special_pos]);
                if printable_len > 0 {
                    terminal.grid.write_ascii_run(
                        &remaining[..printable_len],
                        terminal.active_fg,
                        terminal.active_bg,
                        terminal.active_flags,
                        terminal.active_underline_color,
                        terminal.active_hyperlink,
                    );
                    idx += printable_len;
                    continue;
                }

                // If non-ASCII bytes precede the special characters or printable ASCII,
                // chunk them together and pass to the parser directly without 1-byte thrashing.
                let chunk_len = remaining[..special_pos]
                    .iter()
                    .position(|&b| (0x20..=0x7e).contains(&b))
                    .unwrap_or(special_pos);

                let chunk = &remaining[..chunk_len];
                if (0x90..=0x9F).contains(&chunk[0]) {
                    self.in_escape = true;
                }
                let mut performer = Performer {
                    terminal,
                    in_escape: &mut self.in_escape,
                };
                self.parser.advance(&mut performer, chunk);
                idx += chunk_len;
                continue;
            }

            match remaining[0] {
                b'\n' | 0x0B | 0x0C => {
                    terminal.grid.newline_with_bg(terminal.active_bg);
                    terminal.grid.carriage_return();
                    idx += 1;
                }
                b'\r' => {
                    terminal.grid.carriage_return();
                    idx += 1;
                }
                b'\t' => {
                    terminal.grid.tab();
                    idx += 1;
                }
                b'\x08' => {
                    terminal.grid.backspace();
                    idx += 1;
                }
                b'\x07' => {
                    idx += 1;
                }
                b'\x1b' => {
                    self.in_escape = true;
                    // Check if remaining slice starts with CSI ("\x1b[") and find its terminator (0x40..=0x7E)
                    if remaining.len() >= 2
                        && remaining[1] == b'['
                        && let Some(final_idx) = remaining[2..]
                            .iter()
                            .position(|&b| (0x40..=0x7e).contains(&b))
                    {
                        let end = 2 + final_idx;
                        let mut performer = Performer {
                            terminal,
                            in_escape: &mut self.in_escape,
                        };
                        self.parser.advance(&mut performer, &remaining[..=end]);
                        idx += end + 1;
                        continue;
                    }
                    let mut performer = Performer {
                        terminal,
                        in_escape: &mut self.in_escape,
                    };
                    self.parser.advance(&mut performer, &remaining[..1]);
                    idx += 1;
                }
                byte => {
                    if (0x90..=0x9F).contains(&byte) {
                        self.in_escape = true;
                    }
                    let mut performer = Performer {
                        terminal,
                        in_escape: &mut self.in_escape,
                    };
                    self.parser.advance(&mut performer, &remaining[..1]);
                    idx += 1;
                }
            }
        }
    }
}

struct Performer<'a> {
    terminal: &'a mut Terminal,
    in_escape: &'a mut bool,
}

impl Perform for Performer<'_> {
    #[inline]
    fn print(&mut self, c: char) {
        *self.in_escape = false;
        self.terminal.print(c);
    }

    #[inline]
    fn execute(&mut self, byte: u8) {
        *self.in_escape = false;
        self.terminal.execute(byte);
    }

    #[inline]
    fn hook(&mut self, params: &Params, intermediates: &[u8], ignore: bool, action: char) {
        *self.in_escape = true;
        self.terminal.hook(params, intermediates, ignore, action);
    }

    #[inline]
    fn put(&mut self, byte: u8) {
        *self.in_escape = true;
        self.terminal.put(byte);
    }

    #[inline]
    fn unhook(&mut self) {
        *self.in_escape = false;
        self.terminal.unhook();
    }

    #[inline]
    fn osc_dispatch(&mut self, params: &[&[u8]], bell_terminated: bool) {
        *self.in_escape = false;
        self.terminal.osc_dispatch(params, bell_terminated);
    }

    #[inline]
    fn csi_dispatch(&mut self, params: &Params, intermediates: &[u8], ignore: bool, action: char) {
        *self.in_escape = false;
        self.terminal
            .csi_dispatch(params, intermediates, ignore, action);
    }

    #[inline]
    fn esc_dispatch(&mut self, intermediates: &[u8], ignore: bool, byte: u8) {
        *self.in_escape = false;
        self.terminal.esc_dispatch(intermediates, ignore, byte);
    }
}

impl Perform for Terminal {
    #[inline]
    fn print(&mut self, c: char) {
        self.grid.write_char_styled(
            c,
            self.active_fg,
            self.active_bg,
            self.active_flags,
            self.active_underline_color,
            self.active_hyperlink,
        );
    }

    fn execute(&mut self, byte: u8) {
        match byte {
            b'\n' | 0x0B | 0x0C => {
                self.grid.newline_with_bg(self.active_bg);
                self.grid.carriage_return();
            }
            b'\r' => self.grid.carriage_return(),
            b'\x08' => self.grid.backspace(),
            b'\t' => self.grid.tab(),
            b'\x07' => {} // Bell
            _ => {}
        }
    }

    fn hook(&mut self, _params: &Params, _intermediates: &[u8], _ignore: bool, _action: char) {}

    fn put(&mut self, _byte: u8) {}

    fn unhook(&mut self) {}

    fn osc_dispatch(&mut self, params: &[&[u8]], bell_terminated: bool) {
        self.handle_osc(params, bell_terminated);
    }

    fn csi_dispatch(&mut self, params: &Params, intermediates: &[u8], ignore: bool, action: char) {
        self.handle_csi(params, intermediates, ignore, action);
    }

    fn esc_dispatch(&mut self, _intermediates: &[u8], _ignore: bool, byte: u8) {
        match byte {
            b'7' => self.grid.save_cursor(),
            b'8' => self.grid.restore_cursor(),
            b'M' => {
                // Reverse Index
                if self.grid.cursor.row == self.grid.scroll_region_top {
                    self.grid.scroll_down_with_bg(1, self.active_bg);
                } else {
                    self.grid.cursor.row = self.grid.cursor.row.saturating_sub(1);
                }
            }
            b'c' => {
                // Full Reset (RIS)
                self.grid.clear_screen(ClearMode::All);
                self.grid.cursor = crate::grid::Cursor::default();
                self.mouse = MouseState::default();
                self.bracketed_paste = false;
                self.focus_reporting = false;
                self.synchronized_output = false;
                self.current_dir = None;
                self.shell_integration = None;
                self.report_color_scheme = false;
                self.report_window_size = false;
                self.progress = None;
                self.active_hyperlink = None;
                self.grid.clear_all_hyperlinks();
                self.grid.prompt_marks.clear();
                self.hyperlinks_by_url.clear();
                self.hyperlinks_by_id.clear();
                self.hyperlink_order.clear();
                self.title.clear();
                self.title_dirty = true;
                self.default_fg = self.initial_default_fg;
                self.default_bg = self.initial_default_bg;
                self.palette = self.initial_palette;
                self.palette_dirty = true;
                self.next_hyperlink_id = 1;
                self.kitty_keyboard_flags = 0;
                self.kitty_keyboard_stack.clear();
                self.pending_kitty_keyboard = Some((0, 1));
                self.reset_attributes();
            }
            _ => {}
        }
    }
}

// --- CSI Handler ---

pub(crate) const MAX_KEYBOARD_STACK_DEPTH: usize = 64;
pub(crate) const SUPPORTED_KITTY_FLAGS: u16 = (1 | 2) as u16;

impl Terminal {
    pub(crate) fn handle_csi(
        &mut self,
        params: &Params,
        intermediates: &[u8],
        _ignore: bool,
        action: char,
    ) {
        let is_private = intermediates.contains(&b'?');
        let mut flat_params_buf = [0u16; 32];
        let mut flat_len = 0;
        for param in params.iter() {
            for &val in param {
                if flat_len < flat_params_buf.len() {
                    flat_params_buf[flat_len] = val;
                    flat_len += 1;
                }
            }
        }
        let flat_params = &flat_params_buf[..flat_len];

        let first_param = flat_params.first().copied().unwrap_or(0);
        let param_or = |default: usize| -> usize {
            if first_param == 0 {
                default
            } else {
                first_param as usize
            }
        };

        if is_private {
            if action == 'u' {
                // CSI ? u - Query Kitty keyboard protocol flags
                self.responses
                    .push(format!("\x1b[?{}u", self.kitty_keyboard_flags).into_bytes());
                return;
            }
            if intermediates.contains(&b'$') && action == 'p' {
                // DECRQM - Request DEC Private Mode
                for mode in flat_params {
                    let status = match *mode {
                        25 => {
                            if self.grid.cursor.visible {
                                1
                            } else {
                                2
                            }
                        }
                        1004 => {
                            if self.focus_reporting {
                                1
                            } else {
                                2
                            }
                        }
                        1049 => {
                            if self.grid.is_alt_screen() {
                                1
                            } else {
                                2
                            }
                        }
                        2004 => {
                            if self.bracketed_paste {
                                1
                            } else {
                                2
                            }
                        }
                        2026 => {
                            if self.synchronized_output {
                                1
                            } else {
                                2
                            }
                        }
                        2031 => {
                            if self.report_color_scheme {
                                1
                            } else {
                                2
                            }
                        }
                        2048 => {
                            if self.report_window_size {
                                1
                            } else {
                                2
                            }
                        }
                        _ => 0, // Not recognized
                    };
                    self.responses
                        .push(format!("\x1b[?{};{}$y", mode, status).into_bytes());
                }
                return;
            }
            if action == 'h' || action == 'l' {
                let enabled = action == 'h';
                for mode in flat_params {
                    match *mode {
                        25 => self.grid.cursor.visible = enabled,
                        1049 => {
                            if enabled {
                                self.grid.enter_alt_screen();
                            } else {
                                self.grid.exit_alt_screen();
                            }
                        }
                        1004 => self.focus_reporting = enabled,
                        2004 => self.bracketed_paste = enabled,
                        2026 => {
                            if enabled {
                                self.sync_output_gen = self.sync_output_gen.wrapping_add(1);
                            }
                            self.synchronized_output = enabled;
                        }
                        2031 => {
                            self.report_color_scheme = enabled;
                            if enabled {
                                self.send_color_scheme_report();
                            }
                        }
                        2048 => {
                            self.report_window_size = enabled;
                            if enabled {
                                let current_size = (
                                    [self.grid.rows, self.grid.cols],
                                    [self.viewport_pixels[1], self.viewport_pixels[0]],
                                );
                                self.last_reported_window_size = Some(current_size);
                                self.responses.push(
                                    format!(
                                        "\x1b[48;{};{};{};{}t",
                                        self.grid.rows,
                                        self.grid.cols,
                                        self.viewport_pixels[1],
                                        self.viewport_pixels[0]
                                    )
                                    .into_bytes(),
                                );
                            } else {
                                self.last_reported_window_size = None;
                            }
                        }
                        _ => {
                            self.mouse.apply_private_mode(*mode, enabled);
                        }
                    }
                }
            }
            return;
        }

        if action == 'u' {
            if intermediates.contains(&b'>') && flat_params.len() <= 1 {
                // CSI > flags u - Push Kitty keyboard flags
                let raw = flat_params.first().copied().unwrap_or(0);
                let flags = (raw & SUPPORTED_KITTY_FLAGS) as u8;
                if self.kitty_keyboard_stack.len() >= MAX_KEYBOARD_STACK_DEPTH {
                    self.kitty_keyboard_stack.remove(0);
                }
                self.kitty_keyboard_stack.push(self.kitty_keyboard_flags);
                self.kitty_keyboard_flags = flags;
                self.pending_kitty_keyboard = Some((flags, 1));
                return;
            } else if intermediates.contains(&b'=') || intermediates.contains(&b'>') {
                // CSI = flags ; mode u  or  CSI > flags ; mode u
                let raw = flat_params.first().copied().unwrap_or(0);
                let flags = (raw & SUPPORTED_KITTY_FLAGS) as u8;
                let mode = flat_params.get(1).copied().unwrap_or(1) as u8;
                match mode {
                    1 => self.kitty_keyboard_flags = flags,
                    2 => self.kitty_keyboard_flags |= flags,
                    3 => self.kitty_keyboard_flags &= !flags,
                    _ => {}
                }
                self.pending_kitty_keyboard = Some((flags, mode));
                return;
            } else if intermediates.contains(&b'<') {
                // CSI < count u - Pop Kitty keyboard flags
                let count = flat_params.first().copied().unwrap_or(1).max(1) as usize;
                for _ in 0..count {
                    if let Some(f) = self.kitty_keyboard_stack.pop() {
                        self.kitty_keyboard_flags = f;
                    } else {
                        // Empty stack resets to 0 according to Kitty keyboard protocol
                        self.kitty_keyboard_flags = 0;
                    }
                }
                self.pending_kitty_keyboard = Some((self.kitty_keyboard_flags, 1));
                return;
            }
        }

        match action {
            // CUU - Cursor Up
            'A' => {
                let count = param_or(1);
                self.grid.cursor.row = self.grid.cursor.row.saturating_sub(count);
            }
            // CUD - Cursor Down
            'B' => {
                let count = param_or(1);
                self.grid.cursor.row =
                    (self.grid.cursor.row + count).min(self.grid.rows.saturating_sub(1));
            }
            // CUF - Cursor Forward
            'C' => {
                let count = param_or(1);
                self.grid.cursor.col =
                    (self.grid.cursor.col + count).min(self.grid.cols.saturating_sub(1));
            }
            // CUB - Cursor Back
            'D' => {
                let count = param_or(1);
                self.grid.cursor.col = self.grid.cursor.col.saturating_sub(count);
            }
            // CNL - Cursor Next Line
            'E' => {
                let count = param_or(1);
                self.grid.cursor.row =
                    (self.grid.cursor.row + count).min(self.grid.rows.saturating_sub(1));
                self.grid.cursor.col = 0;
            }
            // CPL - Cursor Previous Line
            'F' => {
                let count = param_or(1);
                self.grid.cursor.row = self.grid.cursor.row.saturating_sub(count);
                self.grid.cursor.col = 0;
            }
            // CHA / HPA - Cursor Character Absolute
            'G' | '\'' => {
                let col = param_or(1).saturating_sub(1);
                self.grid.cursor.col = col.min(self.grid.cols.saturating_sub(1));
            }
            // CUP / HVP - Cursor Position
            'H' | 'f' => {
                let row = flat_params
                    .first()
                    .copied()
                    .unwrap_or(1)
                    .max(1)
                    .saturating_sub(1) as usize;
                let col = flat_params
                    .get(1)
                    .copied()
                    .unwrap_or(1)
                    .max(1)
                    .saturating_sub(1) as usize;
                self.grid.cursor.row = row.min(self.grid.rows.saturating_sub(1));
                self.grid.cursor.col = col.min(self.grid.cols.saturating_sub(1));
            }
            // ED - Erase in Display
            'J' => {
                let mode = match first_param {
                    1 => ClearMode::Above,
                    2 => ClearMode::All,
                    3 => ClearMode::Saved,
                    _ => ClearMode::Below,
                };
                self.grid.clear_screen_with_bg(mode, self.active_bg);
            }
            // EL - Erase in Line
            'K' => {
                let mode = match first_param {
                    1 => ClearMode::Above,
                    2 => ClearMode::All,
                    _ => ClearMode::Below,
                };
                self.grid.clear_line_with_bg(mode, self.active_bg);
            }
            // IL - Insert Lines
            'L' => self.grid.insert_lines_with_bg(param_or(1), self.active_bg),
            // DL - Delete Lines
            'M' => self.grid.delete_lines_with_bg(param_or(1), self.active_bg),
            // DCH - Delete Characters
            'P' => self.grid.delete_chars_with_bg(param_or(1), self.active_bg),
            // ICH - Insert Blank Characters
            '@' => self
                .grid
                .insert_blank_chars_with_bg(param_or(1), self.active_bg),
            // ECH - Erase Characters
            'X' => self.grid.erase_chars_with_bg(param_or(1), self.active_bg),
            // SU - Scroll Up
            'S' => self.grid.scroll_up_with_bg(param_or(1), self.active_bg),
            // SD - Scroll Down
            'T' => self.grid.scroll_down_with_bg(param_or(1), self.active_bg),
            // VPA - Line Position Absolute
            'd' => {
                let row = param_or(1).saturating_sub(1);
                self.grid.cursor.row = row.min(self.grid.rows.saturating_sub(1));
            }
            // DSR - Device Status Report
            'n' => match first_param {
                5 => self.responses.push(b"\x1b[0n".to_vec()),
                6 => self.responses.push(
                    format!(
                        "\x1b[{};{}R",
                        self.grid.cursor.row + 1,
                        self.grid.cursor.col + 1
                    )
                    .into_bytes(),
                ),
                _ => {}
            },
            // DA - Device Attributes
            'c' => {
                if intermediates.contains(&b'>') {
                    // Secondary Device Attributes (DA2)
                    self.responses.push(b"\x1b[>0;10;1c".to_vec());
                } else if first_param == 0 {
                    // Primary Device Attributes (DA1) - VT220 response
                    self.responses.push(b"\x1b[?62;c".to_vec());
                }
            }
            // SGR - Select Graphic Rendition
            'm' => self.handle_sgr(params),
            // DECSTBM - Set Scrolling Region
            'r' => {
                let top = flat_params
                    .first()
                    .copied()
                    .unwrap_or(1)
                    .max(1)
                    .saturating_sub(1) as usize;
                let bottom = flat_params
                    .get(1)
                    .copied()
                    .unwrap_or(self.grid.rows as u16)
                    .max(1)
                    .saturating_sub(1) as usize;
                self.grid.set_scroll_region(top, bottom);
            }
            // Save cursor position
            's' => self.grid.save_cursor(),
            // Restore cursor position
            'u' => self.grid.restore_cursor(),
            // Window manipulation: image clients query pixel geometry before placing images.
            't' => match first_param {
                14 => self.responses.push(
                    format!(
                        "\x1b[4;{};{}t",
                        self.viewport_pixels[1], self.viewport_pixels[0]
                    )
                    .into_bytes(),
                ),
                16 => self.responses.push(
                    format!("\x1b[6;{};{}t", self.cell_pixels[1], self.cell_pixels[0]).into_bytes(),
                ),
                18 => self
                    .responses
                    .push(format!("\x1b[8;{};{}t", self.grid.rows, self.grid.cols).into_bytes()),
                _ => {}
            },
            _ => {}
        }
    }
}

// --- OSC Handler ---

/// Parses an OSC 7 file URI (e.g. `file://localhost/home/user` or `file:///tmp`) into a local PathBuf.
#[must_use]
pub fn parse_osc7_path(raw: &str) -> Option<PathBuf> {
    let stripped = raw.strip_prefix("file://")?;
    let path_str = if let Some(idx) = stripped.find('/') {
        &stripped[idx..]
    } else {
        stripped
    };
    let decoded = percent_decode(path_str)?;
    Some(PathBuf::from(decoded))
}

/// Simple percent-decoding for URL encoded paths.
#[must_use]
pub fn percent_decode(s: &str) -> Option<String> {
    let mut bytes = Vec::with_capacity(s.len());
    let mut chars = s.bytes();
    while let Some(b) = chars.next() {
        if b == b'%' {
            let h1 = chars.next()?;
            let h2 = chars.next()?;
            let hex_bytes = [h1, h2];
            let hex_str = std::str::from_utf8(&hex_bytes).ok()?;
            let byte = u8::from_str_radix(hex_str, 16).ok()?;
            bytes.push(byte);
        } else {
            bytes.push(b);
        }
    }
    String::from_utf8(bytes).ok()
}

impl Terminal {
    pub(crate) fn handle_osc(&mut self, params: &[&[u8]], _bell_terminated: bool) {
        if params.len() >= 2
            && (params[0] == b"0" || params[0] == b"2")
            && let Ok(title) = std::str::from_utf8(params[1])
        {
            self.title = title.to_string();
            self.title_dirty = true;
        } else if !params.is_empty() {
            if params[0] == b"10" && params.len() >= 2 {
                if params[1] == b"?" {
                    let fg = self.default_fg;
                    let resp = format!(
                        "\x1b]10;rgb:{:02x}{:02x}/{:02x}{:02x}/{:02x}{:02x}\x1b\\",
                        fg.r, fg.r, fg.g, fg.g, fg.b, fg.b
                    );
                    self.responses.push(resp.into_bytes());
                } else if let Ok(s) = std::str::from_utf8(params[1])
                    && let Some(color) = crate::color::parse_color_spec(s)
                {
                    self.default_fg = color;
                    self.palette_dirty = true;
                }
            } else if params[0] == b"11" && params.len() >= 2 {
                if params[1] == b"?" {
                    let bg = self.default_bg;
                    let resp = format!(
                        "\x1b]11;rgb:{:02x}{:02x}/{:02x}{:02x}/{:02x}{:02x}\x1b\\",
                        bg.r, bg.r, bg.g, bg.g, bg.b, bg.b
                    );
                    self.responses.push(resp.into_bytes());
                } else if let Ok(s) = std::str::from_utf8(params[1])
                    && let Some(color) = crate::color::parse_color_spec(s)
                {
                    self.update_dynamic_background(color);
                }
            } else if params[0] == b"110" {
                self.default_fg = self.initial_default_fg;
                self.palette_dirty = true;
            } else if params[0] == b"111" {
                self.update_dynamic_background(self.initial_default_bg);
            } else if params[0] == b"4" && params.len() >= 3 {
                for chunk in params[1..].as_chunks::<2>().0 {
                    if let Ok(idx_str) = std::str::from_utf8(chunk[0])
                        && let Ok(idx) = idx_str.parse::<usize>()
                        && idx < 256
                    {
                        if chunk[1] == b"?" {
                            let col = self.palette[idx];
                            let resp = format!(
                                "\x1b]4;{idx};rgb:{:02x}{:02x}/{:02x}{:02x}/{:02x}{:02x}\x1b\\",
                                col.r, col.r, col.g, col.g, col.b, col.b
                            );
                            self.responses.push(resp.into_bytes());
                        } else if let Ok(s) = std::str::from_utf8(chunk[1])
                            && let Some(color) = crate::color::parse_color_spec(s)
                        {
                            self.palette[idx] = color;
                            self.palette_dirty = true;
                        }
                    }
                }
            } else if params[0] == b"104" {
                if params.len() == 1 {
                    self.palette = self.initial_palette;
                    self.palette_dirty = true;
                } else {
                    for param in &params[1..] {
                        if let Ok(s) = std::str::from_utf8(param)
                            && let Ok(idx) = s.parse::<usize>()
                            && idx < 256
                        {
                            self.palette[idx] = self.initial_palette[idx];
                            self.palette_dirty = true;
                        }
                    }
                }
            } else if params[0] == b"52" && params.len() >= 2 {
                // OSC 52 ; [Pc] ; Pd
                let (target, payload) = if params.len() == 2 {
                    (b"c".as_slice(), params[1])
                } else {
                    (params[1], params[2])
                };

                let target_str = std::str::from_utf8(target).unwrap_or("c");
                let primary_target = target_str.chars().next().unwrap_or('c');

                if payload == b"?" {
                    if self.allow_osc52_read {
                        let b64 = self
                            .clipboard_content
                            .as_ref()
                            .map(|text| BASE64_STANDARD.encode(text.as_bytes()))
                            .unwrap_or_default();
                        let resp = format!("\x1b]52;{};{}\x1b\\", primary_target, b64);
                        self.responses.push(resp.into_bytes());
                    }
                } else if payload.is_empty() {
                    if self.allow_osc52_write {
                        self.clipboard_content = None;
                        self.pending_clipboard = Some(None);
                    }
                } else if self.allow_osc52_write
                    && let Ok(decoded) = BASE64_STANDARD.decode(payload)
                    && let Ok(text) = String::from_utf8(decoded)
                {
                    self.clipboard_content = Some(text.clone());
                    self.pending_clipboard = Some(Some(text));
                }
            } else if params[0] == b"7" && params.len() >= 2 {
                // OSC 7 ; file://[hostname]/path
                if let Ok(uri) = std::str::from_utf8(params[1])
                    && let Some(path) = parse_osc7_path(uri)
                {
                    self.current_dir = Some(path);
                }
            } else if params[0] == b"133" && params.len() >= 2 {
                // OSC 133 ; [A|B|C|D] [; exit_code]
                match params[1] {
                    b"A" => {
                        self.shell_integration = Some(ShellIntegrationState::PromptStart);
                        if !self.grid.is_alt_screen() {
                            let abs_line = self.grid.scrollback.len() + self.grid.cursor.row;
                            self.grid.add_prompt_mark(abs_line);
                        }
                    }
                    b"B" => self.shell_integration = Some(ShellIntegrationState::CommandStart),
                    b"C" => self.shell_integration = Some(ShellIntegrationState::OutputStart),
                    b"D" => {
                        let exit_code = if params.len() >= 3 {
                            std::str::from_utf8(params[2])
                                .ok()
                                .and_then(|s| s.parse::<i32>().ok())
                        } else {
                            None
                        };
                        self.shell_integration =
                            Some(ShellIntegrationState::CommandFinished(exit_code));
                    }
                    _ => {}
                }
            } else if params[0] == b"9" && params.len() >= 3 && params[1] == b"4" {
                // OSC 9 ; 4 ; state [; progress]
                let state_val = std::str::from_utf8(params[2])
                    .ok()
                    .and_then(|s| s.parse::<u8>().ok());
                let progress_val = if params.len() >= 4 {
                    std::str::from_utf8(params[3])
                        .ok()
                        .and_then(|s| s.parse::<u8>().ok())
                        .unwrap_or(0)
                        .min(100)
                } else {
                    0
                };
                self.progress = match state_val {
                    Some(0) => None,
                    Some(1) => Some(ProgressState::Normal(progress_val)),
                    Some(2) => Some(ProgressState::Error(progress_val)),
                    Some(3) => Some(ProgressState::Indeterminate),
                    Some(4) => Some(ProgressState::Warning(progress_val)),
                    _ => None,
                };
            } else if params[0] == b"8" {
                // OSC 8 ; [params] ; [url]
                let url_bytes = if params.len() >= 3 {
                    params[2]
                } else if params.len() == 2 {
                    params[1]
                } else {
                    b"".as_slice()
                };

                if url_bytes.is_empty() {
                    self.active_hyperlink = None;
                } else if let Ok(url) = std::str::from_utf8(url_bytes) {
                    let id = self.get_or_intern_hyperlink(url.to_string());
                    self.active_hyperlink = if id > 0 { Some(id) } else { None };
                }
            }
        }
    }
}

// --- SGR Handler ---

impl Terminal {
    pub(crate) fn handle_sgr(&mut self, params: &Params) {
        let mut param_list_buf: [&[u16]; 32] = [&[]; 32];
        let mut param_count = 0;
        for param in params.iter() {
            if param_count < param_list_buf.len() {
                param_list_buf[param_count] = param;
                param_count += 1;
            }
        }
        let param_list = &param_list_buf[..param_count];
        if param_list.is_empty() {
            self.reset_attributes();
            return;
        }

        let mut i = 0;
        while i < param_list.len() {
            let p = param_list[i];
            let code = p.first().copied().unwrap_or(0);
            match code {
                0 => self.reset_attributes(),
                1 => self.active_flags.insert(CellFlags::BOLD),
                2 => self.active_flags.insert(CellFlags::DIM),
                3 => self.active_flags.insert(CellFlags::ITALIC),
                4 => {
                    self.active_flags.remove(CellFlags::ALL_UNDERLINES);
                    if p.len() > 1 {
                        // Subparameters: e.g. 4:3 (undercurl)
                        match p[1] {
                            0 => {}
                            1 => self.active_flags.insert(CellFlags::UNDERLINE),
                            2 => self
                                .active_flags
                                .insert(CellFlags::UNDERLINE | CellFlags::UNDERLINE_DOUBLE),
                            3 => self
                                .active_flags
                                .insert(CellFlags::UNDERLINE | CellFlags::UNDERLINE_CURLY),
                            4 => self
                                .active_flags
                                .insert(CellFlags::UNDERLINE | CellFlags::UNDERLINE_DOTTED),
                            5 => self
                                .active_flags
                                .insert(CellFlags::UNDERLINE | CellFlags::UNDERLINE_DASHED),
                            _ => self.active_flags.insert(CellFlags::UNDERLINE),
                        }
                    } else {
                        // Plain single underline
                        self.active_flags.insert(CellFlags::UNDERLINE);
                    }
                }
                7 => self.active_flags.insert(CellFlags::REVERSE),
                8 => self.active_flags.insert(CellFlags::HIDDEN),
                9 => self.active_flags.insert(CellFlags::STRIKETHROUGH),
                22 => self.active_flags.remove(CellFlags::BOLD | CellFlags::DIM),
                23 => self.active_flags.remove(CellFlags::ITALIC),
                24 => self.active_flags.remove(CellFlags::ALL_UNDERLINES),
                27 => self.active_flags.remove(CellFlags::REVERSE),
                28 => self.active_flags.remove(CellFlags::HIDDEN),
                29 => self.active_flags.remove(CellFlags::STRIKETHROUGH),
                30..=37 => self.active_fg = Color::Indexed((code - 30) as u8),
                38 => {
                    // Extended foreground: colon subparams or semicolon-separated
                    if p.len() >= 3 && p[1] == 5 {
                        self.active_fg = Color::Indexed(p[2] as u8);
                    } else if p.len() >= 5 && p[1] == 2 {
                        let offset = if p.len() >= 6 { 3 } else { 2 };
                        self.active_fg =
                            Color::Rgb(p[offset] as u8, p[offset + 1] as u8, p[offset + 2] as u8);
                    } else if i + 2 < param_list.len() && param_list[i + 1].first() == Some(&5) {
                        if let Some(&idx) = param_list[i + 2].first() {
                            self.active_fg = Color::Indexed(idx as u8);
                            i += 2;
                        }
                    } else if i + 4 < param_list.len() && param_list[i + 1].first() == Some(&2) {
                        let r = param_list[i + 2].first().copied().unwrap_or(0) as u8;
                        let g = param_list[i + 3].first().copied().unwrap_or(0) as u8;
                        let b = param_list[i + 4].first().copied().unwrap_or(0) as u8;
                        self.active_fg = Color::Rgb(r, g, b);
                        i += 4;
                    }
                }
                39 => self.active_fg = Color::DefaultForeground,
                40..=47 => self.active_bg = Color::Indexed((code - 40) as u8),
                48 => {
                    // Extended background: colon subparams or semicolon-separated
                    if p.len() >= 3 && p[1] == 5 {
                        self.active_bg = Color::Indexed(p[2] as u8);
                    } else if p.len() >= 5 && p[1] == 2 {
                        let offset = if p.len() >= 6 { 3 } else { 2 };
                        self.active_bg =
                            Color::Rgb(p[offset] as u8, p[offset + 1] as u8, p[offset + 2] as u8);
                    } else if i + 2 < param_list.len() && param_list[i + 1].first() == Some(&5) {
                        if let Some(&idx) = param_list[i + 2].first() {
                            self.active_bg = Color::Indexed(idx as u8);
                            i += 2;
                        }
                    } else if i + 4 < param_list.len() && param_list[i + 1].first() == Some(&2) {
                        let r = param_list[i + 2].first().copied().unwrap_or(0) as u8;
                        let g = param_list[i + 3].first().copied().unwrap_or(0) as u8;
                        let b = param_list[i + 4].first().copied().unwrap_or(0) as u8;
                        self.active_bg = Color::Rgb(r, g, b);
                        i += 4;
                    }
                }
                49 => self.active_bg = Color::DefaultBackground,
                58 => {
                    // Extended underline color: colon subparams or semicolon-separated
                    if p.len() >= 3 && p[1] == 5 {
                        self.active_underline_color = Color::Indexed(p[2] as u8);
                    } else if p.len() >= 5 && p[1] == 2 {
                        let offset = if p.len() >= 6 { 3 } else { 2 };
                        self.active_underline_color =
                            Color::Rgb(p[offset] as u8, p[offset + 1] as u8, p[offset + 2] as u8);
                    } else if i + 2 < param_list.len() && param_list[i + 1].first() == Some(&5) {
                        if let Some(&idx) = param_list[i + 2].first() {
                            self.active_underline_color = Color::Indexed(idx as u8);
                            i += 2;
                        }
                    } else if i + 4 < param_list.len() && param_list[i + 1].first() == Some(&2) {
                        let r = param_list[i + 2].first().copied().unwrap_or(0) as u8;
                        let g = param_list[i + 3].first().copied().unwrap_or(0) as u8;
                        let b = param_list[i + 4].first().copied().unwrap_or(0) as u8;
                        self.active_underline_color = Color::Rgb(r, g, b);
                        i += 4;
                    }
                }
                59 => self.active_underline_color = Color::DefaultForeground,
                90..=97 => self.active_fg = Color::Indexed((code - 90 + 8) as u8),
                100..=107 => self.active_bg = Color::Indexed((code - 100 + 8) as u8),
                _ => {}
            }
            i += 1;
        }
    }

    pub(crate) fn reset_attributes(&mut self) {
        self.active_fg = Color::DefaultForeground;
        self.active_bg = Color::DefaultBackground;
        self.active_underline_color = Color::DefaultForeground;
        self.active_flags = CellFlags::empty();
    }
}
