//! ANSI / VT escape sequence parser implementing the DEC terminal state machine.

use std::path::PathBuf;

use base64::Engine;
use base64::engine::general_purpose::STANDARD as BASE64_STANDARD;
use vte::{Params, Parser, Perform};

use crate::color::{Color, Rgb};
use crate::grid::{CellFlags, ClearMode, Grid};
use crate::mouse::MouseState;

/// Semantic shell integration state reported through OSC 133.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShellIntegrationState {
    PromptStart,
    CommandStart,
    OutputStart,
    CommandFinished(Option<i32>),
}

/// Terminal emulation state machine combining a screen grid, current formatting attributes,
/// and a VT parser.
pub struct Terminal {
    pub grid: Grid,
    pub active_fg: Color,
    pub active_bg: Color,
    pub active_flags: CellFlags,
    pub mouse: MouseState,
    pub title: String,
    /// Cell size in physical pixels, reported back through `CSI 16 t`.
    pub cell_pixels: [u16; 2],
    /// Text-area size in physical pixels, reported back through `CSI 14 t`.
    pub viewport_pixels: [u16; 2],
    pub default_fg: Rgb,
    pub default_bg: Rgb,
    /// Whether bracketed paste mode (DECSET 2004) is currently enabled.
    pub bracketed_paste: bool,
    /// Whether focus reporting (DECSET 1004) is currently enabled.
    pub focus_reporting: bool,
    /// Whether synchronized output (DECSET 2026) is currently enabled.
    pub synchronized_output: bool,
    /// Internal clipboard content accessible for OSC 52 queries and updates.
    pub clipboard_content: Option<String>,
    /// Pending clipboard content received via OSC 52 awaiting sync with Wayland data device.
    pending_clipboard: Option<String>,
    /// Current working directory reported through OSC 7.
    pub current_dir: Option<PathBuf>,
    /// Shell integration state reported through OSC 133.
    pub shell_integration: Option<ShellIntegrationState>,
    /// Whether color scheme reporting (DECSET 2031) is enabled.
    pub report_color_scheme: bool,
    /// Whether window size notifications (DECSET 2048) are enabled.
    pub report_window_size: bool,
    // Replies generated by the parser (window size reports) awaiting PTY write-back.
    responses: Vec<Vec<u8>>,
    parser: Parser,
}

impl Terminal {
    #[must_use]
    pub fn new(cols: usize, rows: usize, max_scrollback: usize) -> Self {
        Self {
            grid: Grid::new(cols, rows, max_scrollback),
            active_fg: Color::DefaultForeground,
            active_bg: Color::DefaultBackground,
            active_flags: CellFlags::empty(),
            mouse: MouseState::default(),
            title: String::new(),
            cell_pixels: [1, 1],
            viewport_pixels: [1, 1],
            default_fg: Rgb::new(220, 220, 220),
            default_bg: Rgb::new(24, 24, 24),
            bracketed_paste: false,
            focus_reporting: false,
            synchronized_output: false,
            clipboard_content: None,
            pending_clipboard: None,
            current_dir: None,
            shell_integration: None,
            report_color_scheme: false,
            report_window_size: false,
            responses: Vec::new(),
            parser: Parser::new(),
        }
    }

    /// Updates the configured default foreground and background colors for OSC queries.
    pub fn set_default_colors(&mut self, fg: Rgb, bg: Rgb) {
        let old_bg = self.default_bg;
        self.default_fg = fg;
        self.default_bg = bg;
        if self.report_color_scheme
            && self.is_dark_background(old_bg) != self.is_dark_background(bg)
        {
            self.send_color_scheme_report();
        }
    }

    fn is_dark_background(&self, bg: Rgb) -> bool {
        (bg.r as u32 * 299 + bg.g as u32 * 587 + bg.b as u32 * 114) / 1000 < 128
    }

    fn send_color_scheme_report(&mut self) {
        let code = if self.is_dark_background(self.default_bg) {
            1
        } else {
            2
        };
        self.responses
            .push(format!("\x1b[?2031;{}$y", code).into_bytes());
    }

    /// Records the current pixel geometry so clients can size images for this terminal.
    pub fn set_geometry(&mut self, cell_pixels: [u16; 2], viewport_pixels: [u16; 2]) {
        let old_viewport = self.viewport_pixels;
        self.cell_pixels = [cell_pixels[0].max(1), cell_pixels[1].max(1)];
        self.viewport_pixels = viewport_pixels;
        if self.report_window_size && old_viewport != viewport_pixels {
            self.responses.push(
                format!(
                    "\x1b[4;{};{}t",
                    self.viewport_pixels[1], self.viewport_pixels[0]
                )
                .into_bytes(),
            );
        }
    }

    /// Drains replies generated while parsing, for the event loop to write back to the PTY.
    pub fn take_responses(&mut self) -> Vec<Vec<u8>> {
        std::mem::take(&mut self.responses)
    }

    /// Drains pending clipboard updates received through OSC 52.
    pub fn take_pending_clipboard(&mut self) -> Option<String> {
        self.pending_clipboard.take()
    }

    /// Sets the local clipboard content so that OSC 52 queries can return it.
    pub fn set_clipboard_content(&mut self, content: Option<String>) {
        self.clipboard_content = content;
    }

    /// Feeds incoming raw bytes (from PTY) through the VT parser.
    pub fn advance_bytes(&mut self, bytes: &[u8]) {
        let mut parser = std::mem::replace(&mut self.parser, Parser::new());
        parser.advance(self, bytes);
        self.parser = parser;
    }

    fn handle_sgr(&mut self, params: &[u16]) {
        if params.is_empty() {
            self.reset_attributes();
            return;
        }

        let mut i = 0;
        while i < params.len() {
            match params[i] {
                0 => self.reset_attributes(),
                1 => self.active_flags.insert(CellFlags::BOLD),
                2 => self.active_flags.insert(CellFlags::DIM),
                3 => self.active_flags.insert(CellFlags::ITALIC),
                4 => self.active_flags.insert(CellFlags::UNDERLINE),
                7 => self.active_flags.insert(CellFlags::REVERSE),
                8 => self.active_flags.insert(CellFlags::HIDDEN),
                9 => self.active_flags.insert(CellFlags::STRIKETHROUGH),
                22 => self.active_flags.remove(CellFlags::BOLD | CellFlags::DIM),
                23 => self.active_flags.remove(CellFlags::ITALIC),
                24 => self.active_flags.remove(CellFlags::UNDERLINE),
                27 => self.active_flags.remove(CellFlags::REVERSE),
                28 => self.active_flags.remove(CellFlags::HIDDEN),
                29 => self.active_flags.remove(CellFlags::STRIKETHROUGH),
                30..=37 => self.active_fg = Color::Indexed((params[i] - 30) as u8),
                38 => {
                    // Extended foreground
                    if i + 2 < params.len() && params[i + 1] == 5 {
                        self.active_fg = Color::Indexed(params[i + 2] as u8);
                        i += 2;
                    } else if i + 4 < params.len() && params[i + 1] == 2 {
                        self.active_fg = Color::Rgb(
                            params[i + 2] as u8,
                            params[i + 3] as u8,
                            params[i + 4] as u8,
                        );
                        i += 4;
                    }
                }
                39 => self.active_fg = Color::DefaultForeground,
                40..=47 => self.active_bg = Color::Indexed((params[i] - 40) as u8),
                48 => {
                    // Extended background
                    if i + 2 < params.len() && params[i + 1] == 5 {
                        self.active_bg = Color::Indexed(params[i + 2] as u8);
                        i += 2;
                    } else if i + 4 < params.len() && params[i + 1] == 2 {
                        self.active_bg = Color::Rgb(
                            params[i + 2] as u8,
                            params[i + 3] as u8,
                            params[i + 4] as u8,
                        );
                        i += 4;
                    }
                }
                49 => self.active_bg = Color::DefaultBackground,
                90..=97 => self.active_fg = Color::Indexed((params[i] - 90 + 8) as u8),
                100..=107 => self.active_bg = Color::Indexed((params[i] - 100 + 8) as u8),
                _ => {}
            }
            i += 1;
        }
    }

    fn reset_attributes(&mut self) {
        self.active_fg = Color::DefaultForeground;
        self.active_bg = Color::DefaultBackground;
        self.active_flags = CellFlags::empty();
    }
}

/// Parses an OSC 7 file URI (e.g. `file://localhost/home/user` or `file:///tmp`) into a local PathBuf.
fn parse_osc7_path(raw: &str) -> Option<PathBuf> {
    let stripped = raw.strip_prefix("file://")?;
    let path_str = if let Some(idx) = stripped.find('/') {
        &stripped[idx..]
    } else {
        stripped
    };
    let decoded = percent_decode(path_str)?;
    Some(PathBuf::from(decoded))
}

/// Simple percent-decoding for URL encoded paths.
fn percent_decode(s: &str) -> Option<String> {
    let mut bytes = Vec::with_capacity(s.len());
    let mut chars = s.bytes();
    while let Some(b) = chars.next() {
        if b == b'%' {
            let h1 = chars.next()?;
            let h2 = chars.next()?;
            let hex_bytes = [h1, h2];
            let hex_str = std::str::from_utf8(&hex_bytes).ok()?;
            let byte = u8::from_str_radix(hex_str, 16).ok()?;
            bytes.push(byte);
        } else {
            bytes.push(b);
        }
    }
    String::from_utf8(bytes).ok()
}

impl Perform for Terminal {
    fn print(&mut self, c: char) {
        self.grid
            .write_char(c, self.active_fg, self.active_bg, self.active_flags);
    }

    fn execute(&mut self, byte: u8) {
        match byte {
            b'\n' | 0x0B | 0x0C => {
                self.grid.newline();
                self.grid.carriage_return();
            }
            b'\r' => self.grid.carriage_return(),
            b'\x08' => self.grid.backspace(),
            b'\t' => self.grid.tab(),
            b'\x07' => {} // Bell
            _ => {}
        }
    }

    fn hook(&mut self, _params: &Params, _intermediates: &[u8], _ignore: bool, _action: char) {}

    fn put(&mut self, _byte: u8) {}

    fn unhook(&mut self) {}

    fn osc_dispatch(&mut self, params: &[&[u8]], _bell_terminated: bool) {
        if params.len() >= 2
            && (params[0] == b"0" || params[0] == b"2")
            && let Ok(title) = std::str::from_utf8(params[1])
        {
            self.title = title.to_string();
        } else if params.len() >= 2 {
            if params[0] == b"10" && params[1] == b"?" {
                let fg = self.default_fg;
                let resp = format!(
                    "\x1b]10;rgb:{:02x}{:02x}/{:02x}{:02x}/{:02x}{:02x}\x1b\\",
                    fg.r, fg.r, fg.g, fg.g, fg.b, fg.b
                );
                self.responses.push(resp.into_bytes());
            } else if params[0] == b"11" && params[1] == b"?" {
                let bg = self.default_bg;
                let resp = format!(
                    "\x1b]11;rgb:{:02x}{:02x}/{:02x}{:02x}/{:02x}{:02x}\x1b\\",
                    bg.r, bg.r, bg.g, bg.g, bg.b, bg.b
                );
                self.responses.push(resp.into_bytes());
            } else if params[0] == b"52" {
                // OSC 52 ; [Pc] ; Pd
                let (target, payload) = if params.len() == 2 {
                    (b"c".as_slice(), params[1])
                } else {
                    (params[1], params[2])
                };

                let target_str = std::str::from_utf8(target).unwrap_or("c");
                let primary_target = target_str.chars().next().unwrap_or('c');

                if payload == b"?" {
                    let b64 = self
                        .clipboard_content
                        .as_ref()
                        .map(|text| BASE64_STANDARD.encode(text.as_bytes()))
                        .unwrap_or_default();
                    let resp = format!("\x1b]52;{};{}\x1b\\", primary_target, b64);
                    self.responses.push(resp.into_bytes());
                } else if payload.is_empty() {
                    self.clipboard_content = None;
                    self.pending_clipboard = Some(String::new());
                } else if let Ok(decoded) = BASE64_STANDARD.decode(payload)
                    && let Ok(text) = String::from_utf8(decoded)
                {
                    self.clipboard_content = Some(text.clone());
                    self.pending_clipboard = Some(text);
                }
            } else if params[0] == b"7" && params.len() >= 2 {
                // OSC 7 ; file://[hostname]/path
                if let Ok(uri) = std::str::from_utf8(params[1])
                    && let Some(path) = parse_osc7_path(uri)
                {
                    self.current_dir = Some(path);
                }
            } else if params[0] == b"133" && params.len() >= 2 {
                // OSC 133 ; [A|B|C|D] [; exit_code]
                match params[1] {
                    b"A" => self.shell_integration = Some(ShellIntegrationState::PromptStart),
                    b"B" => self.shell_integration = Some(ShellIntegrationState::CommandStart),
                    b"C" => self.shell_integration = Some(ShellIntegrationState::OutputStart),
                    b"D" => {
                        let exit_code = if params.len() >= 3 {
                            std::str::from_utf8(params[2])
                                .ok()
                                .and_then(|s| s.parse::<i32>().ok())
                        } else {
                            None
                        };
                        self.shell_integration =
                            Some(ShellIntegrationState::CommandFinished(exit_code));
                    }
                    _ => {}
                }
            }
        }
    }

    fn csi_dispatch(&mut self, params: &Params, intermediates: &[u8], _ignore: bool, action: char) {
        let is_private = intermediates.contains(&b'?');
        let mut flat_params: Vec<u16> = Vec::new();
        for param in params.iter() {
            flat_params.extend_from_slice(param);
        }

        let first_param = flat_params.first().copied().unwrap_or(0);
        let param_or = |default: usize| -> usize {
            if first_param == 0 {
                default
            } else {
                first_param as usize
            }
        };

        if is_private {
            if intermediates.contains(&b'$') && action == 'p' {
                // DECRQM - Request DEC Private Mode
                for mode in &flat_params {
                    let status = match *mode {
                        25 => {
                            if self.grid.cursor.visible {
                                1
                            } else {
                                2
                            }
                        }
                        1004 => {
                            if self.focus_reporting {
                                1
                            } else {
                                2
                            }
                        }
                        1049 => {
                            if self.grid.is_alt_screen() {
                                1
                            } else {
                                2
                            }
                        }
                        2004 => {
                            if self.bracketed_paste {
                                1
                            } else {
                                2
                            }
                        }
                        2026 => {
                            if self.synchronized_output {
                                1
                            } else {
                                2
                            }
                        }
                        2031 => {
                            if self.report_color_scheme {
                                1
                            } else {
                                2
                            }
                        }
                        2048 => {
                            if self.report_window_size {
                                1
                            } else {
                                2
                            }
                        }
                        _ => 0, // Not recognized
                    };
                    self.responses
                        .push(format!("\x1b[?{};{}$y", mode, status).into_bytes());
                }
                return;
            }
            if action == 'h' || action == 'l' {
                let enabled = action == 'h';
                for mode in &flat_params {
                    match *mode {
                        25 => self.grid.cursor.visible = enabled,
                        1049 => {
                            if enabled {
                                self.grid.enter_alt_screen();
                            } else {
                                self.grid.exit_alt_screen();
                            }
                        }
                        1004 => self.focus_reporting = enabled,
                        2004 => self.bracketed_paste = enabled,
                        2026 => self.synchronized_output = enabled,
                        2031 => {
                            self.report_color_scheme = enabled;
                            if enabled {
                                self.send_color_scheme_report();
                            }
                        }
                        2048 => {
                            self.report_window_size = enabled;
                            if enabled {
                                self.responses.push(
                                    format!(
                                        "\x1b[4;{};{}t",
                                        self.viewport_pixels[1], self.viewport_pixels[0]
                                    )
                                    .into_bytes(),
                                );
                            }
                        }
                        _ => {
                            self.mouse.apply_private_mode(*mode, enabled);
                        }
                    }
                }
            }
            return;
        }

        match action {
            // CUU - Cursor Up
            'A' => {
                let count = param_or(1);
                self.grid.cursor.row = self.grid.cursor.row.saturating_sub(count);
            }
            // CUD - Cursor Down
            'B' => {
                let count = param_or(1);
                self.grid.cursor.row =
                    (self.grid.cursor.row + count).min(self.grid.rows.saturating_sub(1));
            }
            // CUF - Cursor Forward
            'C' => {
                let count = param_or(1);
                self.grid.cursor.col =
                    (self.grid.cursor.col + count).min(self.grid.cols.saturating_sub(1));
            }
            // CUB - Cursor Back
            'D' => {
                let count = param_or(1);
                self.grid.cursor.col = self.grid.cursor.col.saturating_sub(count);
            }
            // CNL - Cursor Next Line
            'E' => {
                let count = param_or(1);
                self.grid.cursor.row =
                    (self.grid.cursor.row + count).min(self.grid.rows.saturating_sub(1));
                self.grid.cursor.col = 0;
            }
            // CPL - Cursor Previous Line
            'F' => {
                let count = param_or(1);
                self.grid.cursor.row = self.grid.cursor.row.saturating_sub(count);
                self.grid.cursor.col = 0;
            }
            // CHA / HPA - Cursor Character Absolute
            'G' | '\'' => {
                let col = param_or(1).saturating_sub(1);
                self.grid.cursor.col = col.min(self.grid.cols.saturating_sub(1));
            }
            // CUP / HVP - Cursor Position
            'H' | 'f' => {
                let row = flat_params
                    .first()
                    .copied()
                    .unwrap_or(1)
                    .max(1)
                    .saturating_sub(1) as usize;
                let col = flat_params
                    .get(1)
                    .copied()
                    .unwrap_or(1)
                    .max(1)
                    .saturating_sub(1) as usize;
                self.grid.cursor.row = row.min(self.grid.rows.saturating_sub(1));
                self.grid.cursor.col = col.min(self.grid.cols.saturating_sub(1));
            }
            // ED - Erase in Display
            'J' => {
                let mode = match first_param {
                    1 => ClearMode::Above,
                    2 => ClearMode::All,
                    3 => ClearMode::Saved,
                    _ => ClearMode::Below,
                };
                self.grid.clear_screen(mode);
            }
            // EL - Erase in Line
            'K' => {
                let mode = match first_param {
                    1 => ClearMode::Above,
                    2 => ClearMode::All,
                    _ => ClearMode::Below,
                };
                self.grid.clear_line(mode);
            }
            // IL - Insert Lines
            'L' => self.grid.insert_lines(param_or(1)),
            // DL - Delete Lines
            'M' => self.grid.delete_lines(param_or(1)),
            // DCH - Delete Characters
            'P' => self.grid.delete_chars(param_or(1)),
            // ICH - Insert Blank Characters
            '@' => self.grid.insert_blank_chars(param_or(1)),
            // SU - Scroll Up
            'S' => self.grid.scroll_up(param_or(1)),
            // SD - Scroll Down
            'T' => self.grid.scroll_down(param_or(1)),
            // VPA - Line Position Absolute
            'd' => {
                let row = param_or(1).saturating_sub(1);
                self.grid.cursor.row = row.min(self.grid.rows.saturating_sub(1));
            }
            // DSR - Device Status Report
            'n' => match first_param {
                5 => self.responses.push(b"\x1b[0n".to_vec()),
                6 => self.responses.push(
                    format!(
                        "\x1b[{};{}R",
                        self.grid.cursor.row + 1,
                        self.grid.cursor.col + 1
                    )
                    .into_bytes(),
                ),
                _ => {}
            },
            // DA - Device Attributes
            'c' => {
                if intermediates.contains(&b'>') {
                    // Secondary Device Attributes (DA2)
                    self.responses.push(b"\x1b[>0;10;1c".to_vec());
                } else if first_param == 0 {
                    // Primary Device Attributes (DA1) - VT220 response
                    self.responses.push(b"\x1b[?62;c".to_vec());
                }
            }
            // SGR - Select Graphic Rendition
            'm' => self.handle_sgr(&flat_params),
            // DECSTBM - Set Scrolling Region
            'r' => {
                let top = flat_params
                    .first()
                    .copied()
                    .unwrap_or(1)
                    .max(1)
                    .saturating_sub(1) as usize;
                let bottom = flat_params
                    .get(1)
                    .copied()
                    .unwrap_or(self.grid.rows as u16)
                    .max(1)
                    .saturating_sub(1) as usize;
                self.grid.set_scroll_region(top, bottom);
            }
            // Save cursor position
            's' => self.grid.save_cursor(),
            // Restore cursor position
            'u' => self.grid.restore_cursor(),
            // Window manipulation: image clients query pixel geometry before placing images.
            't' => match first_param {
                14 => self.responses.push(
                    format!(
                        "\x1b[4;{};{}t",
                        self.viewport_pixels[1], self.viewport_pixels[0]
                    )
                    .into_bytes(),
                ),
                16 => self.responses.push(
                    format!("\x1b[6;{};{}t", self.cell_pixels[1], self.cell_pixels[0]).into_bytes(),
                ),
                18 => self
                    .responses
                    .push(format!("\x1b[8;{};{}t", self.grid.rows, self.grid.cols).into_bytes()),
                _ => {}
            },
            _ => {}
        }
    }

    fn esc_dispatch(&mut self, _intermediates: &[u8], _ignore: bool, byte: u8) {
        match byte {
            b'7' => self.grid.save_cursor(),
            b'8' => self.grid.restore_cursor(),
            b'M' => {
                // Reverse Index
                if self.grid.cursor.row == self.grid.scroll_region_top {
                    self.grid.scroll_down(1);
                } else {
                    self.grid.cursor.row = self.grid.cursor.row.saturating_sub(1);
                }
            }
            b'c' => {
                // Full Reset (RIS)
                self.grid.clear_screen(ClearMode::All);
                self.grid.cursor = crate::grid::Cursor::default();
                self.mouse = MouseState::default();
                self.bracketed_paste = false;
                self.focus_reporting = false;
                self.synchronized_output = false;
                self.current_dir = None;
                self.shell_integration = None;
                self.report_color_scheme = false;
                self.report_window_size = false;
                self.reset_attributes();
            }
            _ => {}
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_print_and_cursor_movement() {
        let mut term = Terminal::new(80, 24, 100);
        term.advance_bytes(b"Hello, World!\r\nSecond line");

        assert_eq!(term.grid.lines[0].cells[0].c, 'H');
        assert_eq!(term.grid.lines[0].cells[12].c, '!');
        assert_eq!(term.grid.lines[1].cells[0].c, 'S');
        assert_eq!(term.grid.cursor.row, 1);
        assert_eq!(term.grid.cursor.col, 11);
    }

    #[test]
    fn test_sgr_formatting() {
        let mut term = Terminal::new(80, 24, 100);
        // Set bold, red fg (31), truecolor bg (48;2;10;20;30)
        term.advance_bytes(b"\x1b[1;31;48;2;10;20;30mX\x1b[0m");

        let cell = term.grid.lines[0].cells[0];
        assert_eq!(cell.c, 'X');
        assert!(cell.flags.contains(CellFlags::BOLD));
        assert_eq!(cell.fg, Color::Indexed(1));
        assert_eq!(cell.bg, Color::Rgb(10, 20, 30));

        // After reset
        assert_eq!(term.active_fg, Color::DefaultForeground);
        assert_eq!(term.active_bg, Color::DefaultBackground);
        assert_eq!(term.active_flags, CellFlags::empty());
    }

    #[test]
    fn test_osc_title() {
        let mut term = Terminal::new(80, 24, 100);
        term.advance_bytes(b"\x1b]0;ftty terminal\x07");
        assert_eq!(term.title, "ftty terminal");
    }

    #[test]
    fn window_geometry_queries_are_answered_in_height_width_order() {
        let mut term = Terminal::new(80, 24, 100);
        term.set_geometry([9, 18], [720, 432]);
        term.advance_bytes(b"\x1b[14t\x1b[16t\x1b[18t");

        let responses = term.take_responses();
        assert_eq!(
            responses,
            vec![
                b"\x1b[4;432;720t".to_vec(),
                b"\x1b[6;18;9t".to_vec(),
                b"\x1b[8;24;80t".to_vec(),
            ]
        );
        // Draining resets the queue so replies are written exactly once.
        assert!(term.take_responses().is_empty());

        // Unrelated window manipulations stay silent.
        term.advance_bytes(b"\x1b[22;0t\x1b[23;0t");
        assert!(term.take_responses().is_empty());
    }

    #[test]
    fn test_mouse_tracking_modes() {
        use crate::mouse::{MouseEncoding, MouseTracking};

        let mut term = Terminal::new(80, 24, 100);
        assert!(!term.mouse.is_reporting());

        term.advance_bytes(b"\x1b[?1002h\x1b[?1006h");
        assert_eq!(term.mouse.tracking, MouseTracking::Drag);
        assert_eq!(term.mouse.encoding, MouseEncoding::Sgr);
        assert!(term.mouse.is_reporting());

        // Bundled private modes must all be applied.
        term.advance_bytes(b"\x1b[?1002l\x1b[?1006l");
        assert!(!term.mouse.is_reporting());
        assert_eq!(term.mouse.encoding, MouseEncoding::X10);

        term.advance_bytes(b"\x1b[?1000;1006h");
        assert_eq!(term.mouse.tracking, MouseTracking::Click);
        assert_eq!(term.mouse.encoding, MouseEncoding::Sgr);

        // A full reset returns to local selection.
        term.advance_bytes(b"\x1bc");
        assert!(!term.mouse.is_reporting());
        assert_eq!(term.mouse.encoding, MouseEncoding::X10);
    }

    #[test]
    fn test_cursor_visibility_does_not_disturb_mouse_modes() {
        let mut term = Terminal::new(80, 24, 100);
        term.advance_bytes(b"\x1b[?1000h\x1b[?25l");
        assert!(term.mouse.is_reporting());
        assert!(!term.grid.cursor.visible);
    }

    #[test]
    fn test_clear_screen_csi() {
        let mut term = Terminal::new(80, 24, 100);
        term.advance_bytes(b"Testing\x1b[2J");
        assert_eq!(term.grid.lines[0].cells[0].c, ' ');
    }

    #[test]
    fn test_device_status_and_attributes_queries() {
        let mut term = Terminal::new(80, 24, 100);

        // CSI 5 n -> Operating status (DSR)
        term.advance_bytes(b"\x1b[5n");
        assert_eq!(term.take_responses(), vec![b"\x1b[0n".to_vec()]);

        // CSI 6 n -> Cursor position report (CPR)
        term.advance_bytes(b"\x1b[10;20H\x1b[6n");
        assert_eq!(term.take_responses(), vec![b"\x1b[10;20R".to_vec()]);

        // Primary DA: CSI c
        term.advance_bytes(b"\x1b[c");
        assert_eq!(term.take_responses(), vec![b"\x1b[?62;c".to_vec()]);

        // Secondary DA: CSI > c
        term.advance_bytes(b"\x1b[>c");
        assert_eq!(term.take_responses(), vec![b"\x1b[>0;10;1c".to_vec()]);
    }

    #[test]
    fn test_osc_color_queries_use_configured_defaults() {
        let mut term = Terminal::new(80, 24, 100);
        term.set_default_colors(Rgb::new(255, 128, 0), Rgb::new(10, 20, 30));

        term.advance_bytes(b"\x1b]10;?\x07");
        assert_eq!(
            term.take_responses(),
            vec![b"\x1b]10;rgb:ffff/8080/0000\x1b\\".to_vec()]
        );

        term.advance_bytes(b"\x1b]11;?\x07");
        assert_eq!(
            term.take_responses(),
            vec![b"\x1b]11;rgb:0a0a/1414/1e1e\x1b\\".to_vec()]
        );
    }

    #[test]
    fn test_bracketed_paste_mode_toggle() {
        let mut term = Terminal::new(80, 24, 100);
        assert!(!term.bracketed_paste);

        term.advance_bytes(b"\x1b[?2004h");
        assert!(term.bracketed_paste);

        term.advance_bytes(b"\x1b[?2004l");
        assert!(!term.bracketed_paste);

        // Bundled private modes
        term.advance_bytes(b"\x1b[?25;2004h");
        assert!(term.bracketed_paste);
        assert!(term.grid.cursor.visible);

        // Full reset disables bracketed paste
        term.advance_bytes(b"\x1bc");
        assert!(!term.bracketed_paste);
    }

    #[test]
    fn test_focus_reporting_mode_toggle() {
        let mut term = Terminal::new(80, 24, 100);
        assert!(!term.focus_reporting);

        term.advance_bytes(b"\x1b[?1004h");
        assert!(term.focus_reporting);

        term.advance_bytes(b"\x1b[?1004l");
        assert!(!term.focus_reporting);

        // Full reset disables focus reporting
        term.advance_bytes(b"\x1b[?1004h\x1bc");
        assert!(!term.focus_reporting);
    }

    #[test]
    fn test_synchronized_output_and_decrqm_queries() {
        let mut term = Terminal::new(80, 24, 100);
        assert!(!term.synchronized_output);

        // Query mode 2026 before setting: disabled (2)
        term.advance_bytes(b"\x1b[?2026$p");
        assert_eq!(term.take_responses(), vec![b"\x1b[?2026;2$y".to_vec()]);

        // Enable mode 2026
        term.advance_bytes(b"\x1b[?2026h");
        assert!(term.synchronized_output);

        // Query mode 2026 after setting: enabled (1)
        term.advance_bytes(b"\x1b[?2026$p");
        assert_eq!(term.take_responses(), vec![b"\x1b[?2026;1$y".to_vec()]);

        // Disable mode 2026
        term.advance_bytes(b"\x1b[?2026l");
        assert!(!term.synchronized_output);

        // Query unrecognized mode -> 0
        term.advance_bytes(b"\x1b[?9999$p");
        assert_eq!(term.take_responses(), vec![b"\x1b[?9999;0$y".to_vec()]);
    }

    #[test]
    fn test_osc_52_clipboard_read_and_write() {
        let mut term = Terminal::new(80, 24, 100);

        // Query empty clipboard
        term.advance_bytes(b"\x1b]52;c;?\x07");
        assert_eq!(term.take_responses(), vec![b"\x1b]52;c;\x1b\\".to_vec()]);

        // Write "hello world" (aGVsbG8gd29ybGQ=)
        term.advance_bytes(b"\x1b]52;c;aGVsbG8gd29ybGQ=\x07");
        assert_eq!(term.clipboard_content.as_deref(), Some("hello world"));
        assert_eq!(
            term.take_pending_clipboard().as_deref(),
            Some("hello world")
        );

        // Query populated clipboard
        term.advance_bytes(b"\x1b]52;c;?\x1b\\");
        assert_eq!(
            term.take_responses(),
            vec![b"\x1b]52;c;aGVsbG8gd29ybGQ=\x1b\\".to_vec()]
        );

        // Clear clipboard
        term.advance_bytes(b"\x1b]52;c;\x07");
        assert_eq!(term.clipboard_content, None);
        assert_eq!(term.take_pending_clipboard().as_deref(), Some(""));
    }

    #[test]
    fn test_osc_7_current_working_directory() {
        let mut term = Terminal::new(80, 24, 100);
        assert_eq!(term.current_dir, None);

        // Typical file URI with hostname
        term.advance_bytes(b"\x1b]7;file://archlinux/home/user/projects\x07");
        assert_eq!(
            term.current_dir.as_deref(),
            Some(std::path::Path::new("/home/user/projects"))
        );

        // Percent-encoded spaces and UTF-8
        term.advance_bytes(b"\x1b]7;file:///home/user/my%20documents\x1b\\");
        assert_eq!(
            term.current_dir.as_deref(),
            Some(std::path::Path::new("/home/user/my documents"))
        );

        // Full reset clears current dir
        term.advance_bytes(b"\x1bc");
        assert_eq!(term.current_dir, None);
    }

    #[test]
    fn test_osc_133_shell_integration() {
        let mut term = Terminal::new(80, 24, 100);
        assert_eq!(term.shell_integration, None);

        term.advance_bytes(b"\x1b]133;A\x07");
        assert_eq!(
            term.shell_integration,
            Some(ShellIntegrationState::PromptStart)
        );

        term.advance_bytes(b"\x1b]133;B\x07");
        assert_eq!(
            term.shell_integration,
            Some(ShellIntegrationState::CommandStart)
        );

        term.advance_bytes(b"\x1b]133;C\x07");
        assert_eq!(
            term.shell_integration,
            Some(ShellIntegrationState::OutputStart)
        );

        term.advance_bytes(b"\x1b]133;D;0\x07");
        assert_eq!(
            term.shell_integration,
            Some(ShellIntegrationState::CommandFinished(Some(0)))
        );

        term.advance_bytes(b"\x1b]133;D;127\x1b\\");
        assert_eq!(
            term.shell_integration,
            Some(ShellIntegrationState::CommandFinished(Some(127)))
        );

        // Full reset clears shell integration
        term.advance_bytes(b"\x1bc");
        assert_eq!(term.shell_integration, None);
    }

    #[test]
    fn test_mode_2031_color_scheme_report() {
        let mut term = Terminal::new(80, 24, 100);
        // Default bg is (24, 24, 24) which is dark -> 1
        term.advance_bytes(b"\x1b[?2031h");
        assert!(term.report_color_scheme);
        assert_eq!(term.take_responses(), vec![b"\x1b[?2031;1$y".to_vec()]);

        // Switching to light background reports 2
        term.set_default_colors(Rgb::new(0, 0, 0), Rgb::new(240, 240, 240));
        assert_eq!(term.take_responses(), vec![b"\x1b[?2031;2$y".to_vec()]);

        // DECRQM query
        term.advance_bytes(b"\x1b[?2031$p");
        assert_eq!(term.take_responses(), vec![b"\x1b[?2031;1$y".to_vec()]);

        term.advance_bytes(b"\x1b[?2031l");
        assert!(!term.report_color_scheme);
    }

    #[test]
    fn test_mode_2048_window_size_notifications() {
        let mut term = Terminal::new(80, 24, 100);
        term.set_geometry([10, 20], [800, 600]);

        term.advance_bytes(b"\x1b[?2048h");
        assert!(term.report_window_size);
        assert_eq!(term.take_responses(), vec![b"\x1b[4;600;800t".to_vec()]);

        // Resizing geometry emits notification
        term.set_geometry([10, 20], [1024, 768]);
        assert_eq!(term.take_responses(), vec![b"\x1b[4;768;1024t".to_vec()]);

        term.advance_bytes(b"\x1b[?2048l");
        assert!(!term.report_window_size);
    }
}
